################################################################################
# create_vitis_project.tcl
# -------------------------
# XSCT script: creates a Vitis standalone platform + MicroBlaze application,
# builds the ELF, and programs it onto the Nexys A7 via JTAG.
#
# Prerequisites:
#   1. Vitis 2024.1 (or later) installed  (provides xsct, mb-gcc, BSP libraries)
#      Default path: C:\Xilinx\Vitis\2024.1\bin\xsct.bat
#   2. Bitstream already programmed onto the FPGA  (run program_fpga.tcl first,
#      OR let this script do it via the -bitstream option below)
#   3. XSA file present at:
#        ../03_vivado_hardware/vivado_project/brain_tumor_soc.xsa
#      NOTE: XSA was generated by Vivado 2023.1 – Vitis 2024.1 will show a
#      version-mismatch warning but will still proceed correctly.
#
# Usage (from Vitis 2024.1 xsct):
#   xsct create_vitis_project.tcl
#
# Or from a shell with Vitis on PATH:
#   xsct 04_vitis_software/create_vitis_project.tcl
################################################################################

# ==============================================================================
# Paths
# ==============================================================================
set SCRIPT_DIR [file dirname [file normalize [info script]]]
set XSA_FILE   [file normalize "$SCRIPT_DIR/../03_vivado_hardware/vivado_project/brain_tumor_soc.xsa"]
set BIT_FILE   [file normalize "$SCRIPT_DIR/../03_vivado_hardware/vivado_project/brain_tumor_soc.runs/impl_1/microblaze_soc_wrapper.bit"]
set WS_DIR     "C:/vws/brain_tumor"
set SRC_DIR    "$SCRIPT_DIR/src"

set PLATFORM_NAME "brain_tumor_platform"
set APP_NAME      "brain_tumor_app"
set PROC_NAME     "microblaze_0"
set OS_NAME       "standalone"

# ==============================================================================
# Validate inputs
# ==============================================================================
if { ![file exists $XSA_FILE] } {
    error "XSA not found: $XSA_FILE\n  Run 03_vivado_hardware/build.tcl first."
}

puts "INFO: XSA     = $XSA_FILE"
puts "INFO: SRC     = $SRC_DIR"
puts "INFO: Workspace = $WS_DIR"

# ==============================================================================
# Set workspace
# ==============================================================================
setws $WS_DIR

# ==============================================================================
# Step 1 – Create hardware platform from XSA
# ==============================================================================
puts "INFO: Creating platform '$PLATFORM_NAME'..."
platform create -name $PLATFORM_NAME \
    -hw $XSA_FILE \
    -proc $PROC_NAME \
    -os $OS_NAME \
    -out $WS_DIR

platform write

# ==============================================================================
# Step 2 – Generate BSP (Board Support Package)
# ==============================================================================
puts "INFO: Generating and building BSP (this takes ~1-2 min)..."
platform generate

# ==============================================================================
# Step 3 – Create application project
# ==============================================================================
puts "INFO: Creating application '$APP_NAME'..."
app create -name $APP_NAME \
    -platform $PLATFORM_NAME \
    -domain ${OS_NAME}_domain \
    -proc $PROC_NAME \
    -os $OS_NAME \
    -template "Empty Application(C)"

# ==============================================================================
# Step 4 – Add all source files
# ==============================================================================
puts "INFO: Adding source files from $SRC_DIR..."
foreach f [glob -nocomplain $SRC_DIR/*.c $SRC_DIR/*.h] {
    importsources -name $APP_NAME -path $f -target-path src
    puts "  Added: [file tail $f]"
}

# ==============================================================================
# Step 5 – Build
# ==============================================================================
puts "INFO: Building application..."
app build -name $APP_NAME

set ELF_FILE "$WS_DIR/$APP_NAME/Debug/${APP_NAME}.elf"
if { ![file exists $ELF_FILE] } {
    error "Build failed – ELF not found at: $ELF_FILE"
}
puts "INFO: ELF built: $ELF_FILE"

# ==============================================================================
# Step 6 – Connect to hardware and download ELF
# ==============================================================================
puts "INFO: Connecting to hardware (JTAG)..."
connect

# Program bitstream: must target the FPGA device (xc7a*), NOT the processor.
# The MicroBlaze target only becomes stable after the bitstream is live.
if { [file exists $BIT_FILE] } {
    puts "INFO: Programming bitstream: $BIT_FILE"
    targets -set -nocase -filter {name =~ "xc7a*"}
    fpga $BIT_FILE
    after 2000
    # Disconnect and reconnect so hw_server re-enumerates the JTAG chain
    # and discovers the MicroBlaze embedded debug core.
    disconnect
    connect
    after 1000
} else {
    puts "INFO: Bitstream not found – assuming already programmed, refreshing targets..."
    disconnect
    connect
    after 1000
}

# Now switch to MicroBlaze to reset and download the ELF.
puts "INFO: Targeting MicroBlaze processor..."
targets -set -nocase -filter {name =~ "*MicroBlaze*"}

rst -processor

# Download ELF
puts "INFO: Downloading ELF to MicroBlaze..."
dow $ELF_FILE

# Run
puts "INFO: Starting application..."
con

puts ""
puts "=============================================="
puts "  Application running on MicroBlaze!"
puts "  Open a serial terminal at 115200 baud on"
puts "  the Nexys A7 USB-UART port to see output."
puts "=============================================="
