// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module otsu_threshold_top_dilate_3x3_linebuf (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        src_address0,
        src_ce0,
        src_q0,
        dst_address1,
        dst_ce1,
        dst_we1,
        dst_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] src_address0;
output   src_ce0;
input  [7:0] src_q0;
output  [13:0] dst_address1;
output   dst_ce1;
output   dst_we1;
output  [7:0] dst_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln347_fu_191_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] icmp_ln347_reg_603;
wire    ap_block_pp0_stage0_11001;
wire   [6:0] col_fu_208_p1;
reg   [6:0] col_reg_607;
wire   [7:0] trunc_ln_fu_212_p4;
reg   [7:0] trunc_ln_reg_612;
reg   [0:0] tmp_reg_617;
wire   [0:0] icmp_ln372_fu_240_p2;
reg   [0:0] icmp_ln372_reg_627;
reg   [6:0] line_buf_addr_reg_632;
wire   [0:0] icmp_ln381_fu_252_p2;
reg   [0:0] icmp_ln381_reg_638;
reg   [6:0] line_buf_1_addr_reg_642;
wire   [0:0] and_ln395_fu_274_p2;
reg   [0:0] and_ln395_reg_648;
reg   [0:0] and_ln395_reg_648_pp0_iter1_reg;
reg   [0:0] and_ln395_reg_648_pp0_iter2_reg;
wire   [6:0] out_col_fu_323_p2;
reg   [6:0] out_col_reg_652;
reg   [6:0] out_col_reg_652_pp0_iter2_reg;
wire   [7:0] v22_fu_406_p3;
reg   [7:0] v22_reg_657;
reg   [7:0] v22_reg_657_pp0_iter2_reg;
wire   [7:0] m01_fu_420_p3;
reg   [7:0] m01_reg_663;
wire   [7:0] m23_fu_434_p3;
reg   [7:0] m23_reg_669;
wire   [7:0] m45_fu_448_p3;
reg   [7:0] m45_reg_675;
wire   [7:0] m67_fu_462_p3;
reg   [7:0] m67_reg_681;
wire   [6:0] trunc_ln425_fu_470_p1;
reg   [6:0] trunc_ln425_reg_687;
reg   [6:0] trunc_ln425_reg_687_pp0_iter2_reg;
wire   [7:0] m01234567_fu_530_p3;
reg   [7:0] m01234567_reg_692;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [6:0] line_buf_address0;
wire   [7:0] line_buf_q0;
wire   [6:0] line_buf_address1;
wire   [6:0] line_buf_1_address0;
wire   [7:0] line_buf_1_q0;
wire   [6:0] line_buf_1_address1;
reg   [7:0] ap_phi_mux_v12_phi_fu_175_p4;
reg   [7:0] ap_phi_reg_pp0_iter1_v12_reg_171;
wire   [7:0] ap_phi_reg_pp0_iter0_v12_reg_171;
wire   [63:0] zext_ln347_fu_203_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln392_fu_246_p1;
wire   [63:0] zext_ln425_fu_555_p1;
reg   [7:0] empty_fu_70;
reg   [7:0] empty_44_fu_74;
reg   [7:0] empty_45_fu_78;
reg   [14:0] i_fu_82;
wire   [14:0] add_ln347_fu_197_p2;
wire    ap_loop_init;
reg   [14:0] ap_sig_allocacmp_i_5;
reg   [7:0] empty_46_fu_86;
wire   [7:0] empty_48_fu_302_p3;
reg   [7:0] v11_fu_90;
reg   [7:0] empty_47_fu_94;
wire   [7:0] new_pixel_2_fu_294_p3;
reg    src_ce0_local;
reg    line_buf_ce0_local;
reg    line_buf_we1_local;
reg    line_buf_ce1_local;
reg    line_buf_1_ce0_local;
reg    line_buf_1_we1_local;
reg    line_buf_1_ce1_local;
reg    dst_we1_local;
wire   [7:0] result_fu_542_p3;
reg    dst_ce1_local;
wire   [6:0] tmp_499_fu_230_p4;
wire   [5:0] tmp_500_fu_258_p4;
wire   [0:0] icmp_ln395_fu_268_p2;
wire   [7:0] out_row_fu_318_p2;
wire   [0:0] icmp_ln401_fu_328_p2;
wire   [0:0] icmp_ln401_1_fu_334_p2;
wire   [0:0] and_ln401_fu_340_p2;
wire   [0:0] icmp_ln407_fu_378_p2;
wire   [0:0] and_ln407_fu_384_p2;
wire   [7:0] v00_fu_346_p3;
wire   [7:0] v01_fu_354_p3;
wire   [0:0] icmp_ln214_fu_414_p2;
wire   [7:0] v02_fu_362_p3;
wire   [7:0] v10_fu_370_p3;
wire   [0:0] icmp_ln214_1_fu_428_p2;
wire   [0:0] icmp_ln214_2_fu_442_p2;
wire   [7:0] v20_fu_390_p3;
wire   [7:0] v21_fu_398_p3;
wire   [0:0] icmp_ln214_3_fu_456_p2;
wire   [0:0] icmp_ln214_4_fu_504_p2;
wire   [0:0] icmp_ln214_5_fu_514_p2;
wire   [7:0] m0123_fu_508_p3;
wire   [7:0] m4567_fu_518_p3;
wire   [0:0] icmp_ln214_6_fu_524_p2;
wire   [0:0] icmp_ln214_7_fu_538_p2;
wire   [13:0] add_ln_fu_549_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_36;
reg    ap_enable_state1_pp0_iter0_stage0;
reg    ap_enable_operation_55;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_predicate_op58_store_state2;
reg    ap_enable_operation_58;
reg    ap_predicate_op40_load_state1;
reg    ap_enable_operation_40;
reg    ap_predicate_op57_load_state2;
reg    ap_enable_operation_57;
reg    ap_enable_operation_60;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_162;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 empty_fu_70 = 8'd0;
#0 empty_44_fu_74 = 8'd0;
#0 empty_45_fu_78 = 8'd0;
#0 i_fu_82 = 15'd0;
#0 empty_46_fu_86 = 8'd0;
#0 v11_fu_90 = 8'd0;
#0 empty_47_fu_94 = 8'd0;
#0 ap_done_reg = 1'b0;
end

otsu_threshold_top_erode_3x3_linebuf_line_buf_RAM_S2P_LUTRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
line_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buf_address0),
    .ce0(line_buf_ce0_local),
    .q0(line_buf_q0),
    .address1(line_buf_address1),
    .ce1(line_buf_ce1_local),
    .we1(line_buf_we1_local),
    .d1(line_buf_1_q0)
);

otsu_threshold_top_erode_3x3_linebuf_line_buf_RAM_S2P_LUTRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
line_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buf_1_address0),
    .ce0(line_buf_1_ce0_local),
    .q0(line_buf_1_q0),
    .address1(line_buf_1_address1),
    .ce1(line_buf_1_ce1_local),
    .we1(line_buf_1_we1_local),
    .d1(new_pixel_2_fu_294_p3)
);

otsu_threshold_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_162)) begin
        if (((icmp_ln381_fu_252_p2 == 1'd1) & (icmp_ln347_fu_191_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_v12_reg_171 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_v12_reg_171 <= ap_phi_reg_pp0_iter0_v12_reg_171;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln347_fu_191_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            i_fu_82 <= add_ln347_fu_197_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_82 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln395_reg_648 <= and_ln395_fu_274_p2;
        and_ln395_reg_648_pp0_iter1_reg <= and_ln395_reg_648;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        col_reg_607 <= col_fu_208_p1;
        icmp_ln347_reg_603 <= icmp_ln347_fu_191_p2;
        icmp_ln372_reg_627 <= icmp_ln372_fu_240_p2;
        icmp_ln381_reg_638 <= icmp_ln381_fu_252_p2;
        line_buf_1_addr_reg_642 <= zext_ln392_fu_246_p1;
        line_buf_addr_reg_632 <= zext_ln392_fu_246_p1;
        m01_reg_663 <= m01_fu_420_p3;
        m23_reg_669 <= m23_fu_434_p3;
        m45_reg_675 <= m45_fu_448_p3;
        m67_reg_681 <= m67_fu_462_p3;
        out_col_reg_652 <= out_col_fu_323_p2;
        tmp_reg_617 <= ap_sig_allocacmp_i_5[32'd14];
        trunc_ln425_reg_687 <= trunc_ln425_fu_470_p1;
        trunc_ln_reg_612 <= {{ap_sig_allocacmp_i_5[14:7]}};
        v22_reg_657 <= v22_fu_406_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln395_reg_648_pp0_iter2_reg <= and_ln395_reg_648_pp0_iter1_reg;
        m01234567_reg_692 <= m01234567_fu_530_p3;
        out_col_reg_652_pp0_iter2_reg <= out_col_reg_652;
        trunc_ln425_reg_687_pp0_iter2_reg <= trunc_ln425_reg_687;
        v22_reg_657_pp0_iter2_reg <= v22_reg_657;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln347_reg_603 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_44_fu_74 <= v11_fu_90;
        empty_45_fu_78 <= empty_47_fu_94;
        empty_46_fu_86 <= empty_48_fu_302_p3;
        empty_47_fu_94 <= new_pixel_2_fu_294_p3;
        empty_fu_70 <= empty_46_fu_86;
        v11_fu_90 <= ap_phi_mux_v12_phi_fu_175_p4;
    end
end

always @ (*) begin
    if (((icmp_ln347_fu_191_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln347_reg_603 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln381_reg_638 == 1'd0) & (icmp_ln347_reg_603 == 1'd0))) begin
        ap_phi_mux_v12_phi_fu_175_p4 = line_buf_1_q0;
    end else begin
        ap_phi_mux_v12_phi_fu_175_p4 = ap_phi_reg_pp0_iter1_v12_reg_171;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_5 = 15'd0;
    end else begin
        ap_sig_allocacmp_i_5 = i_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        dst_ce1_local = 1'b1;
    end else begin
        dst_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln395_reg_648_pp0_iter2_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        dst_we1_local = 1'b1;
    end else begin
        dst_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_1_ce0_local = 1'b1;
    end else begin
        line_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_1_ce1_local = 1'b1;
    end else begin
        line_buf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln347_reg_603 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_1_we1_local = 1'b1;
    end else begin
        line_buf_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_ce0_local = 1'b1;
    end else begin
        line_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_ce1_local = 1'b1;
    end else begin
        line_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln381_reg_638 == 1'd0) & (icmp_ln347_reg_603 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_we1_local = 1'b1;
    end else begin
        line_buf_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_ce0_local = 1'b1;
    end else begin
        src_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln347_fu_197_p2 = (ap_sig_allocacmp_i_5 + 15'd1);

assign add_ln_fu_549_p3 = {{trunc_ln425_reg_687_pp0_iter2_reg}, {out_col_reg_652_pp0_iter2_reg}};

assign and_ln395_fu_274_p2 = (icmp_ln395_fu_268_p2 & icmp_ln372_fu_240_p2);

assign and_ln401_fu_340_p2 = (icmp_ln401_fu_328_p2 & icmp_ln401_1_fu_334_p2);

assign and_ln407_fu_384_p2 = (icmp_ln407_fu_378_p2 & icmp_ln401_1_fu_334_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_162 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

always @ (*) begin
    ap_enable_operation_36 = (icmp_ln347_fu_191_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_40 = (ap_predicate_op40_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_55 = (icmp_ln347_reg_603 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_57 = (ap_predicate_op57_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_58 = (ap_predicate_op58_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_60 = (icmp_ln347_reg_603 == 1'd0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state1_pp0_iter0_stage0 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_v12_reg_171 = 'bx;

always @ (*) begin
    ap_predicate_op40_load_state1 = ((icmp_ln381_fu_252_p2 == 1'd0) & (icmp_ln347_fu_191_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op57_load_state2 = ((icmp_ln381_reg_638 == 1'd0) & (icmp_ln347_reg_603 == 1'd0));
end

always @ (*) begin
    ap_predicate_op58_store_state2 = ((icmp_ln381_reg_638 == 1'd0) & (icmp_ln347_reg_603 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign col_fu_208_p1 = ap_sig_allocacmp_i_5[6:0];

assign dst_address1 = zext_ln425_fu_555_p1;

assign dst_ce1 = dst_ce1_local;

assign dst_d1 = result_fu_542_p3;

assign dst_we1 = dst_we1_local;

assign empty_48_fu_302_p3 = ((icmp_ln372_reg_627[0:0] == 1'b1) ? line_buf_q0 : 8'd0);

assign icmp_ln214_1_fu_428_p2 = ((v02_fu_362_p3 > v10_fu_370_p3) ? 1'b1 : 1'b0);

assign icmp_ln214_2_fu_442_p2 = ((v11_fu_90 > ap_phi_mux_v12_phi_fu_175_p4) ? 1'b1 : 1'b0);

assign icmp_ln214_3_fu_456_p2 = ((v20_fu_390_p3 > v21_fu_398_p3) ? 1'b1 : 1'b0);

assign icmp_ln214_4_fu_504_p2 = ((m01_reg_663 > m23_reg_669) ? 1'b1 : 1'b0);

assign icmp_ln214_5_fu_514_p2 = ((m45_reg_675 > m67_reg_681) ? 1'b1 : 1'b0);

assign icmp_ln214_6_fu_524_p2 = ((m0123_fu_508_p3 > m4567_fu_518_p3) ? 1'b1 : 1'b0);

assign icmp_ln214_7_fu_538_p2 = ((m01234567_reg_692 > v22_reg_657_pp0_iter2_reg) ? 1'b1 : 1'b0);

assign icmp_ln214_fu_414_p2 = ((v00_fu_346_p3 > v01_fu_354_p3) ? 1'b1 : 1'b0);

assign icmp_ln347_fu_191_p2 = ((ap_sig_allocacmp_i_5 == 15'd16640) ? 1'b1 : 1'b0);

assign icmp_ln372_fu_240_p2 = ((tmp_499_fu_230_p4 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln381_fu_252_p2 = ((trunc_ln_fu_212_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln395_fu_268_p2 = ((tmp_500_fu_258_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln401_1_fu_334_p2 = ((out_col_fu_323_p2 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln401_fu_328_p2 = (($signed(out_row_fu_318_p2) > $signed(8'd0)) ? 1'b1 : 1'b0);

assign icmp_ln407_fu_378_p2 = ((out_row_fu_318_p2 != 8'd127) ? 1'b1 : 1'b0);

assign line_buf_1_address0 = zext_ln392_fu_246_p1;

assign line_buf_1_address1 = line_buf_1_addr_reg_642;

assign line_buf_address0 = zext_ln392_fu_246_p1;

assign line_buf_address1 = line_buf_addr_reg_632;

assign m01234567_fu_530_p3 = ((icmp_ln214_6_fu_524_p2[0:0] == 1'b1) ? m0123_fu_508_p3 : m4567_fu_518_p3);

assign m0123_fu_508_p3 = ((icmp_ln214_4_fu_504_p2[0:0] == 1'b1) ? m01_reg_663 : m23_reg_669);

assign m01_fu_420_p3 = ((icmp_ln214_fu_414_p2[0:0] == 1'b1) ? v00_fu_346_p3 : v01_fu_354_p3);

assign m23_fu_434_p3 = ((icmp_ln214_1_fu_428_p2[0:0] == 1'b1) ? v02_fu_362_p3 : v10_fu_370_p3);

assign m4567_fu_518_p3 = ((icmp_ln214_5_fu_514_p2[0:0] == 1'b1) ? m45_reg_675 : m67_reg_681);

assign m45_fu_448_p3 = ((icmp_ln214_2_fu_442_p2[0:0] == 1'b1) ? v11_fu_90 : ap_phi_mux_v12_phi_fu_175_p4);

assign m67_fu_462_p3 = ((icmp_ln214_3_fu_456_p2[0:0] == 1'b1) ? v20_fu_390_p3 : v21_fu_398_p3);

assign new_pixel_2_fu_294_p3 = ((tmp_reg_617[0:0] == 1'b1) ? 8'd0 : src_q0);

assign out_col_fu_323_p2 = ($signed(col_reg_607) + $signed(7'd126));

assign out_row_fu_318_p2 = ($signed(trunc_ln_reg_612) + $signed(8'd254));

assign result_fu_542_p3 = ((icmp_ln214_7_fu_538_p2[0:0] == 1'b1) ? m01234567_reg_692 : v22_reg_657_pp0_iter2_reg);

assign src_address0 = zext_ln347_fu_203_p1;

assign src_ce0 = src_ce0_local;

assign tmp_499_fu_230_p4 = {{ap_sig_allocacmp_i_5[14:8]}};

assign tmp_500_fu_258_p4 = {{ap_sig_allocacmp_i_5[6:1]}};

assign trunc_ln425_fu_470_p1 = out_row_fu_318_p2[6:0];

assign trunc_ln_fu_212_p4 = {{ap_sig_allocacmp_i_5[14:7]}};

assign v00_fu_346_p3 = ((and_ln401_fu_340_p2[0:0] == 1'b1) ? empty_fu_70 : 8'd0);

assign v01_fu_354_p3 = ((icmp_ln401_fu_328_p2[0:0] == 1'b1) ? empty_46_fu_86 : 8'd0);

assign v02_fu_362_p3 = ((icmp_ln401_fu_328_p2[0:0] == 1'b1) ? empty_48_fu_302_p3 : 8'd0);

assign v10_fu_370_p3 = ((icmp_ln401_1_fu_334_p2[0:0] == 1'b1) ? empty_44_fu_74 : 8'd0);

assign v20_fu_390_p3 = ((and_ln407_fu_384_p2[0:0] == 1'b1) ? empty_45_fu_78 : 8'd0);

assign v21_fu_398_p3 = ((icmp_ln407_fu_378_p2[0:0] == 1'b1) ? empty_47_fu_94 : 8'd0);

assign v22_fu_406_p3 = ((icmp_ln407_fu_378_p2[0:0] == 1'b1) ? new_pixel_2_fu_294_p3 : 8'd0);

assign zext_ln347_fu_203_p1 = ap_sig_allocacmp_i_5;

assign zext_ln392_fu_246_p1 = col_fu_208_p1;

assign zext_ln425_fu_555_p1 = add_ln_fu_549_p3;

endmodule //otsu_threshold_top_dilate_3x3_linebuf
