// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module otsu_threshold_top_otsu_threshold_top_Pipeline_SUM_VAR (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        local_in_address0,
        local_in_ce0,
        local_in_q0,
        zext_ln284_1,
        var_sum_out,
        var_sum_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] local_in_address0;
output   local_in_ce0;
input  [7:0] local_in_q0;
input  [7:0] zext_ln284_1;
output  [47:0] var_sum_out;
output   var_sum_out_ap_vld;

reg ap_idle;
reg var_sum_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln284_fu_95_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [8:0] zext_ln284_1_cast_fu_78_p1;
reg   [8:0] zext_ln284_1_cast_reg_175;
reg   [0:0] icmp_ln284_reg_180;
reg   [0:0] icmp_ln284_reg_180_pp0_iter1_reg;
wire   [8:0] diff_fu_121_p2;
reg   [8:0] diff_reg_189;
wire   [17:0] mul_ln288_fu_129_p2;
reg   [17:0] mul_ln288_reg_194;
wire   [63:0] zext_ln284_fu_107_p1;
wire    ap_block_pp0_stage0;
reg   [47:0] var_sum_fu_44;
wire   [47:0] var_sum_1_fu_145_p2;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [16:0] i_fu_48;
wire   [16:0] add_ln284_fu_101_p2;
reg   [16:0] ap_sig_allocacmp_i_2;
wire    ap_block_pp0_stage0_01001;
reg    local_in_ce0_local;
wire   [8:0] zext_ln287_fu_117_p1;
wire  signed [8:0] mul_ln288_fu_129_p0;
wire  signed [17:0] sext_ln288_fu_126_p1;
wire  signed [8:0] mul_ln288_fu_129_p1;
wire  signed [31:0] sext_ln288_1_fu_138_p1;
wire   [47:0] zext_ln288_fu_141_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 var_sum_fu_44 = 48'd0;
#0 i_fu_48 = 17'd0;
#0 ap_done_reg = 1'b0;
end

otsu_threshold_top_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U33(
    .din0(mul_ln288_fu_129_p0),
    .din1(mul_ln288_fu_129_p1),
    .dout(mul_ln288_fu_129_p2)
);

otsu_threshold_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln284_fu_95_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_48 <= add_ln284_fu_101_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_48 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            var_sum_fu_44 <= 48'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            var_sum_fu_44 <= var_sum_1_fu_145_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        diff_reg_189 <= diff_fu_121_p2;
        icmp_ln284_reg_180 <= icmp_ln284_fu_95_p2;
        icmp_ln284_reg_180_pp0_iter1_reg <= icmp_ln284_reg_180;
        zext_ln284_1_cast_reg_175[7 : 0] <= zext_ln284_1_cast_fu_78_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        mul_ln288_reg_194 <= mul_ln288_fu_129_p2;
    end
end

always @ (*) begin
    if (((icmp_ln284_fu_95_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 17'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_ce0_local = 1'b1;
    end else begin
        local_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln284_reg_180_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        var_sum_out_ap_vld = 1'b1;
    end else begin
        var_sum_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln284_fu_101_p2 = (ap_sig_allocacmp_i_2 + 17'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign diff_fu_121_p2 = (zext_ln287_fu_117_p1 - zext_ln284_1_cast_reg_175);

assign icmp_ln284_fu_95_p2 = ((ap_sig_allocacmp_i_2 == 17'd65536) ? 1'b1 : 1'b0);

assign local_in_address0 = zext_ln284_fu_107_p1;

assign local_in_ce0 = local_in_ce0_local;

assign mul_ln288_fu_129_p0 = sext_ln288_fu_126_p1;

assign mul_ln288_fu_129_p1 = sext_ln288_fu_126_p1;

assign sext_ln288_1_fu_138_p1 = $signed(mul_ln288_reg_194);

assign sext_ln288_fu_126_p1 = $signed(diff_reg_189);

assign var_sum_1_fu_145_p2 = (zext_ln288_fu_141_p1 + var_sum_fu_44);

assign var_sum_out = var_sum_fu_44;

assign zext_ln284_1_cast_fu_78_p1 = zext_ln284_1;

assign zext_ln284_fu_107_p1 = ap_sig_allocacmp_i_2;

assign zext_ln287_fu_117_p1 = local_in_q0;

assign zext_ln288_fu_141_p1 = $unsigned(sext_ln288_1_fu_138_p1);

always @ (posedge ap_clk) begin
    zext_ln284_1_cast_reg_175[8] <= 1'b0;
end

endmodule //otsu_threshold_top_otsu_threshold_top_Pipeline_SUM_VAR
