// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module otsu_threshold_top_apply_threshold (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_in_address0,
        img_in_ce0,
        img_in_q0,
        img_out_0_address1,
        img_out_0_ce1,
        img_out_0_we1,
        img_out_0_d1,
        img_out_1_address1,
        img_out_1_ce1,
        img_out_1_we1,
        img_out_1_d1,
        img_out_2_address1,
        img_out_2_ce1,
        img_out_2_we1,
        img_out_2_d1,
        img_out_3_address1,
        img_out_3_ce1,
        img_out_3_we1,
        img_out_3_d1,
        img_out_4_address1,
        img_out_4_ce1,
        img_out_4_we1,
        img_out_4_d1,
        img_out_5_address1,
        img_out_5_ce1,
        img_out_5_we1,
        img_out_5_d1,
        img_out_6_address1,
        img_out_6_ce1,
        img_out_6_we1,
        img_out_6_d1,
        img_out_7_address1,
        img_out_7_ce1,
        img_out_7_we1,
        img_out_7_d1,
        img_out_8_address1,
        img_out_8_ce1,
        img_out_8_we1,
        img_out_8_d1,
        img_out_9_address1,
        img_out_9_ce1,
        img_out_9_we1,
        img_out_9_d1,
        img_out_10_address1,
        img_out_10_ce1,
        img_out_10_we1,
        img_out_10_d1,
        thr
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] img_in_address0;
output   img_in_ce0;
input  [7:0] img_in_q0;
output  [10:0] img_out_0_address1;
output   img_out_0_ce1;
output   img_out_0_we1;
output  [7:0] img_out_0_d1;
output  [10:0] img_out_1_address1;
output   img_out_1_ce1;
output   img_out_1_we1;
output  [7:0] img_out_1_d1;
output  [10:0] img_out_2_address1;
output   img_out_2_ce1;
output   img_out_2_we1;
output  [7:0] img_out_2_d1;
output  [10:0] img_out_3_address1;
output   img_out_3_ce1;
output   img_out_3_we1;
output  [7:0] img_out_3_d1;
output  [10:0] img_out_4_address1;
output   img_out_4_ce1;
output   img_out_4_we1;
output  [7:0] img_out_4_d1;
output  [10:0] img_out_5_address1;
output   img_out_5_ce1;
output   img_out_5_we1;
output  [7:0] img_out_5_d1;
output  [10:0] img_out_6_address1;
output   img_out_6_ce1;
output   img_out_6_we1;
output  [7:0] img_out_6_d1;
output  [10:0] img_out_7_address1;
output   img_out_7_ce1;
output   img_out_7_we1;
output  [7:0] img_out_7_d1;
output  [10:0] img_out_8_address1;
output   img_out_8_ce1;
output   img_out_8_we1;
output  [7:0] img_out_8_d1;
output  [10:0] img_out_9_address1;
output   img_out_9_ce1;
output   img_out_9_we1;
output  [7:0] img_out_9_d1;
output  [10:0] img_out_10_address1;
output   img_out_10_ce1;
output   img_out_10_we1;
output  [7:0] img_out_10_d1;
input  [7:0] thr;

reg ap_idle;
reg img_in_ce0;
reg img_out_0_ce1;
reg img_out_0_we1;
reg img_out_1_ce1;
reg img_out_1_we1;
reg img_out_2_ce1;
reg img_out_2_we1;
reg img_out_3_ce1;
reg img_out_3_we1;
reg img_out_4_ce1;
reg img_out_4_we1;
reg img_out_5_ce1;
reg img_out_5_we1;
reg img_out_6_ce1;
reg img_out_6_we1;
reg img_out_7_ce1;
reg img_out_7_we1;
reg img_out_8_ce1;
reg img_out_8_we1;
reg img_out_9_ce1;
reg img_out_9_we1;
reg img_out_10_ce1;
reg img_out_10_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln119_fu_335_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] trunc_ln119_fu_352_p1;
reg   [3:0] trunc_ln119_reg_478;
reg   [3:0] trunc_ln119_reg_478_pp0_iter1_reg;
wire   [0:0] icmp_ln122_fu_386_p2;
reg   [0:0] icmp_ln122_reg_487;
wire   [63:0] zext_ln119_fu_347_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln119_1_fu_410_p1;
reg   [14:0] phi_urem_fu_96;
wire   [14:0] select_ln119_fu_368_p3;
wire    ap_loop_init;
reg   [14:0] ap_sig_allocacmp_phi_urem_load;
reg   [29:0] phi_mul_fu_100;
wire   [29:0] add_ln119_1_fu_394_p2;
reg   [14:0] i_fu_104;
wire   [14:0] add_ln119_fu_341_p2;
reg   [14:0] ap_sig_allocacmp_i_7;
wire   [7:0] select_ln122_fu_425_p3;
wire   [14:0] add_ln119_2_fu_356_p2;
wire   [0:0] icmp_ln119_1_fu_362_p2;
wire   [10:0] tmp_fu_400_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

otsu_threshold_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln119_fu_335_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_104 <= add_ln119_fu_341_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_104 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            phi_mul_fu_100 <= 30'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            phi_mul_fu_100 <= add_ln119_1_fu_394_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln119_fu_335_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_urem_fu_96 <= select_ln119_fu_368_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_urem_fu_96 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln122_reg_487 <= icmp_ln122_fu_386_p2;
        trunc_ln119_reg_478_pp0_iter1_reg <= trunc_ln119_reg_478;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln119_fu_335_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln119_reg_478 <= trunc_ln119_fu_352_p1;
    end
end

always @ (*) begin
    if (((icmp_ln119_fu_335_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_7 = 15'd0;
    end else begin
        ap_sig_allocacmp_i_7 = i_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_phi_urem_load = 15'd0;
    end else begin
        ap_sig_allocacmp_phi_urem_load = phi_urem_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_in_ce0 = 1'b1;
    end else begin
        img_in_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        img_out_0_ce1 = 1'b1;
    end else begin
        img_out_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln119_reg_478_pp0_iter1_reg == 4'd0))) begin
        img_out_0_we1 = 1'b1;
    end else begin
        img_out_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        img_out_10_ce1 = 1'b1;
    end else begin
        img_out_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & ((trunc_ln119_reg_478_pp0_iter1_reg == 4'd10) | ((trunc_ln119_reg_478_pp0_iter1_reg == 4'd11) | ((trunc_ln119_reg_478_pp0_iter1_reg == 4'd12) | ((trunc_ln119_reg_478_pp0_iter1_reg == 4'd13) | ((trunc_ln119_reg_478_pp0_iter1_reg == 4'd14) | (trunc_ln119_reg_478_pp0_iter1_reg == 4'd15)))))))) begin
        img_out_10_we1 = 1'b1;
    end else begin
        img_out_10_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        img_out_1_ce1 = 1'b1;
    end else begin
        img_out_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln119_reg_478_pp0_iter1_reg == 4'd1))) begin
        img_out_1_we1 = 1'b1;
    end else begin
        img_out_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        img_out_2_ce1 = 1'b1;
    end else begin
        img_out_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln119_reg_478_pp0_iter1_reg == 4'd2))) begin
        img_out_2_we1 = 1'b1;
    end else begin
        img_out_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        img_out_3_ce1 = 1'b1;
    end else begin
        img_out_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln119_reg_478_pp0_iter1_reg == 4'd3))) begin
        img_out_3_we1 = 1'b1;
    end else begin
        img_out_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        img_out_4_ce1 = 1'b1;
    end else begin
        img_out_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln119_reg_478_pp0_iter1_reg == 4'd4))) begin
        img_out_4_we1 = 1'b1;
    end else begin
        img_out_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        img_out_5_ce1 = 1'b1;
    end else begin
        img_out_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln119_reg_478_pp0_iter1_reg == 4'd5))) begin
        img_out_5_we1 = 1'b1;
    end else begin
        img_out_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        img_out_6_ce1 = 1'b1;
    end else begin
        img_out_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln119_reg_478_pp0_iter1_reg == 4'd6))) begin
        img_out_6_we1 = 1'b1;
    end else begin
        img_out_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        img_out_7_ce1 = 1'b1;
    end else begin
        img_out_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln119_reg_478_pp0_iter1_reg == 4'd7))) begin
        img_out_7_we1 = 1'b1;
    end else begin
        img_out_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        img_out_8_ce1 = 1'b1;
    end else begin
        img_out_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln119_reg_478_pp0_iter1_reg == 4'd8))) begin
        img_out_8_we1 = 1'b1;
    end else begin
        img_out_8_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        img_out_9_ce1 = 1'b1;
    end else begin
        img_out_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln119_reg_478_pp0_iter1_reg == 4'd9))) begin
        img_out_9_we1 = 1'b1;
    end else begin
        img_out_9_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln119_1_fu_394_p2 = (phi_mul_fu_100 + 30'd47663);

assign add_ln119_2_fu_356_p2 = (ap_sig_allocacmp_phi_urem_load + 15'd1);

assign add_ln119_fu_341_p2 = (ap_sig_allocacmp_i_7 + 15'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln119_1_fu_362_p2 = ((add_ln119_2_fu_356_p2 < 15'd11) ? 1'b1 : 1'b0);

assign icmp_ln119_fu_335_p2 = ((ap_sig_allocacmp_i_7 == 15'd16384) ? 1'b1 : 1'b0);

assign icmp_ln122_fu_386_p2 = ((img_in_q0 > thr) ? 1'b1 : 1'b0);

assign img_in_address0 = zext_ln119_fu_347_p1;

assign img_out_0_address1 = zext_ln119_1_fu_410_p1;

assign img_out_0_d1 = select_ln122_fu_425_p3;

assign img_out_10_address1 = zext_ln119_1_fu_410_p1;

assign img_out_10_d1 = select_ln122_fu_425_p3;

assign img_out_1_address1 = zext_ln119_1_fu_410_p1;

assign img_out_1_d1 = select_ln122_fu_425_p3;

assign img_out_2_address1 = zext_ln119_1_fu_410_p1;

assign img_out_2_d1 = select_ln122_fu_425_p3;

assign img_out_3_address1 = zext_ln119_1_fu_410_p1;

assign img_out_3_d1 = select_ln122_fu_425_p3;

assign img_out_4_address1 = zext_ln119_1_fu_410_p1;

assign img_out_4_d1 = select_ln122_fu_425_p3;

assign img_out_5_address1 = zext_ln119_1_fu_410_p1;

assign img_out_5_d1 = select_ln122_fu_425_p3;

assign img_out_6_address1 = zext_ln119_1_fu_410_p1;

assign img_out_6_d1 = select_ln122_fu_425_p3;

assign img_out_7_address1 = zext_ln119_1_fu_410_p1;

assign img_out_7_d1 = select_ln122_fu_425_p3;

assign img_out_8_address1 = zext_ln119_1_fu_410_p1;

assign img_out_8_d1 = select_ln122_fu_425_p3;

assign img_out_9_address1 = zext_ln119_1_fu_410_p1;

assign img_out_9_d1 = select_ln122_fu_425_p3;

assign select_ln119_fu_368_p3 = ((icmp_ln119_1_fu_362_p2[0:0] == 1'b1) ? add_ln119_2_fu_356_p2 : 15'd0);

assign select_ln122_fu_425_p3 = ((icmp_ln122_reg_487[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign tmp_fu_400_p4 = {{phi_mul_fu_100[29:19]}};

assign trunc_ln119_fu_352_p1 = ap_sig_allocacmp_phi_urem_load[3:0];

assign zext_ln119_1_fu_410_p1 = tmp_fu_400_p4;

assign zext_ln119_fu_347_p1 = ap_sig_allocacmp_i_7;

endmodule //otsu_threshold_top_apply_threshold
