// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module otsu_threshold_top_otsu_threshold_top_Pipeline_WRITE_OUT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_0_AWVALID,
        m_axi_gmem1_0_AWREADY,
        m_axi_gmem1_0_AWADDR,
        m_axi_gmem1_0_AWID,
        m_axi_gmem1_0_AWLEN,
        m_axi_gmem1_0_AWSIZE,
        m_axi_gmem1_0_AWBURST,
        m_axi_gmem1_0_AWLOCK,
        m_axi_gmem1_0_AWCACHE,
        m_axi_gmem1_0_AWPROT,
        m_axi_gmem1_0_AWQOS,
        m_axi_gmem1_0_AWREGION,
        m_axi_gmem1_0_AWUSER,
        m_axi_gmem1_0_WVALID,
        m_axi_gmem1_0_WREADY,
        m_axi_gmem1_0_WDATA,
        m_axi_gmem1_0_WSTRB,
        m_axi_gmem1_0_WLAST,
        m_axi_gmem1_0_WID,
        m_axi_gmem1_0_WUSER,
        m_axi_gmem1_0_ARVALID,
        m_axi_gmem1_0_ARREADY,
        m_axi_gmem1_0_ARADDR,
        m_axi_gmem1_0_ARID,
        m_axi_gmem1_0_ARLEN,
        m_axi_gmem1_0_ARSIZE,
        m_axi_gmem1_0_ARBURST,
        m_axi_gmem1_0_ARLOCK,
        m_axi_gmem1_0_ARCACHE,
        m_axi_gmem1_0_ARPROT,
        m_axi_gmem1_0_ARQOS,
        m_axi_gmem1_0_ARREGION,
        m_axi_gmem1_0_ARUSER,
        m_axi_gmem1_0_RVALID,
        m_axi_gmem1_0_RREADY,
        m_axi_gmem1_0_RDATA,
        m_axi_gmem1_0_RLAST,
        m_axi_gmem1_0_RID,
        m_axi_gmem1_0_RFIFONUM,
        m_axi_gmem1_0_RUSER,
        m_axi_gmem1_0_RRESP,
        m_axi_gmem1_0_BVALID,
        m_axi_gmem1_0_BREADY,
        m_axi_gmem1_0_BRESP,
        m_axi_gmem1_0_BID,
        m_axi_gmem1_0_BUSER,
        img_out,
        local_out_address0,
        local_out_ce0,
        local_out_q0,
        local_out_1_address0,
        local_out_1_ce0,
        local_out_1_q0,
        local_out_2_address0,
        local_out_2_ce0,
        local_out_2_q0,
        local_out_3_address0,
        local_out_3_ce0,
        local_out_3_q0,
        local_out_4_address0,
        local_out_4_ce0,
        local_out_4_q0,
        local_out_5_address0,
        local_out_5_ce0,
        local_out_5_q0,
        local_out_6_address0,
        local_out_6_ce0,
        local_out_6_q0,
        local_out_7_address0,
        local_out_7_ce0,
        local_out_7_q0,
        local_out_8_address0,
        local_out_8_ce0,
        local_out_8_q0,
        local_out_9_address0,
        local_out_9_ce0,
        local_out_9_q0,
        local_out_10_address0,
        local_out_10_ce0,
        local_out_10_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_0_AWVALID;
input   m_axi_gmem1_0_AWREADY;
output  [63:0] m_axi_gmem1_0_AWADDR;
output  [0:0] m_axi_gmem1_0_AWID;
output  [31:0] m_axi_gmem1_0_AWLEN;
output  [2:0] m_axi_gmem1_0_AWSIZE;
output  [1:0] m_axi_gmem1_0_AWBURST;
output  [1:0] m_axi_gmem1_0_AWLOCK;
output  [3:0] m_axi_gmem1_0_AWCACHE;
output  [2:0] m_axi_gmem1_0_AWPROT;
output  [3:0] m_axi_gmem1_0_AWQOS;
output  [3:0] m_axi_gmem1_0_AWREGION;
output  [0:0] m_axi_gmem1_0_AWUSER;
output   m_axi_gmem1_0_WVALID;
input   m_axi_gmem1_0_WREADY;
output  [7:0] m_axi_gmem1_0_WDATA;
output  [0:0] m_axi_gmem1_0_WSTRB;
output   m_axi_gmem1_0_WLAST;
output  [0:0] m_axi_gmem1_0_WID;
output  [0:0] m_axi_gmem1_0_WUSER;
output   m_axi_gmem1_0_ARVALID;
input   m_axi_gmem1_0_ARREADY;
output  [63:0] m_axi_gmem1_0_ARADDR;
output  [0:0] m_axi_gmem1_0_ARID;
output  [31:0] m_axi_gmem1_0_ARLEN;
output  [2:0] m_axi_gmem1_0_ARSIZE;
output  [1:0] m_axi_gmem1_0_ARBURST;
output  [1:0] m_axi_gmem1_0_ARLOCK;
output  [3:0] m_axi_gmem1_0_ARCACHE;
output  [2:0] m_axi_gmem1_0_ARPROT;
output  [3:0] m_axi_gmem1_0_ARQOS;
output  [3:0] m_axi_gmem1_0_ARREGION;
output  [0:0] m_axi_gmem1_0_ARUSER;
input   m_axi_gmem1_0_RVALID;
output   m_axi_gmem1_0_RREADY;
input  [7:0] m_axi_gmem1_0_RDATA;
input   m_axi_gmem1_0_RLAST;
input  [0:0] m_axi_gmem1_0_RID;
input  [10:0] m_axi_gmem1_0_RFIFONUM;
input  [0:0] m_axi_gmem1_0_RUSER;
input  [1:0] m_axi_gmem1_0_RRESP;
input   m_axi_gmem1_0_BVALID;
output   m_axi_gmem1_0_BREADY;
input  [1:0] m_axi_gmem1_0_BRESP;
input  [0:0] m_axi_gmem1_0_BID;
input  [0:0] m_axi_gmem1_0_BUSER;
input  [63:0] img_out;
output  [12:0] local_out_address0;
output   local_out_ce0;
input  [7:0] local_out_q0;
output  [12:0] local_out_1_address0;
output   local_out_1_ce0;
input  [7:0] local_out_1_q0;
output  [12:0] local_out_2_address0;
output   local_out_2_ce0;
input  [7:0] local_out_2_q0;
output  [12:0] local_out_3_address0;
output   local_out_3_ce0;
input  [7:0] local_out_3_q0;
output  [12:0] local_out_4_address0;
output   local_out_4_ce0;
input  [7:0] local_out_4_q0;
output  [12:0] local_out_5_address0;
output   local_out_5_ce0;
input  [7:0] local_out_5_q0;
output  [12:0] local_out_6_address0;
output   local_out_6_ce0;
input  [7:0] local_out_6_q0;
output  [12:0] local_out_7_address0;
output   local_out_7_ce0;
input  [7:0] local_out_7_q0;
output  [12:0] local_out_8_address0;
output   local_out_8_ce0;
input  [7:0] local_out_8_q0;
output  [12:0] local_out_9_address0;
output   local_out_9_ce0;
input  [7:0] local_out_9_q0;
output  [12:0] local_out_10_address0;
output   local_out_10_ce0;
input  [7:0] local_out_10_q0;

reg ap_idle;
reg m_axi_gmem1_0_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln342_fu_294_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_W;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [12:0] tmp_reg_462;
wire   [7:0] tmp_s_fu_382_p25;
reg   [7:0] tmp_s_reg_522;
wire   [63:0] zext_ln342_fu_341_p1;
wire    ap_block_pp0_stage0_01001_grp1;
reg   [16:0] phi_urem5_fu_116;
wire   [16:0] select_ln344_fu_370_p3;
wire    ap_loop_init;
reg   [16:0] i_fu_120;
wire   [16:0] add_ln342_fu_300_p2;
reg   [16:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage0;
reg    local_out_ce0_local;
reg    local_out_1_ce0_local;
reg    local_out_2_ce0_local;
reg    local_out_3_ce0_local;
reg    local_out_4_ce0_local;
reg    local_out_5_ce0_local;
reg    local_out_6_ce0_local;
reg    local_out_7_ce0_local;
reg    local_out_8_ce0_local;
reg    local_out_9_ce0_local;
reg    local_out_10_ce0_local;
wire   [15:0] trunc_ln342_fu_312_p1;
wire   [15:0] mul_ln342_fu_320_p0;
wire   [17:0] mul_ln342_fu_320_p1;
wire   [32:0] mul_ln342_fu_320_p2;
wire   [0:0] icmp_ln344_fu_364_p2;
wire   [16:0] add_ln344_fu_358_p2;
wire   [7:0] tmp_s_fu_382_p23;
wire   [3:0] tmp_s_fu_382_p24;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [32:0] mul_ln342_fu_320_p00;
wire   [3:0] tmp_s_fu_382_p1;
wire   [3:0] tmp_s_fu_382_p3;
wire   [3:0] tmp_s_fu_382_p5;
wire   [3:0] tmp_s_fu_382_p7;
wire   [3:0] tmp_s_fu_382_p9;
wire   [3:0] tmp_s_fu_382_p11;
wire   [3:0] tmp_s_fu_382_p13;
wire   [3:0] tmp_s_fu_382_p15;
wire  signed [3:0] tmp_s_fu_382_p17;
wire  signed [3:0] tmp_s_fu_382_p19;
wire  signed [3:0] tmp_s_fu_382_p21;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 phi_urem5_fu_116 = 17'd0;
#0 i_fu_120 = 17'd0;
#0 ap_done_reg = 1'b0;
end

otsu_threshold_top_mul_16ns_18ns_33_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 33 ))
mul_16ns_18ns_33_1_1_U168(
    .din0(mul_ln342_fu_320_p0),
    .din1(mul_ln342_fu_320_p1),
    .dout(mul_ln342_fu_320_p2)
);

(* dissolve_hierarchy = "yes" *) otsu_threshold_top_sparsemux_23_4_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 8 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 8 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 8 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
sparsemux_23_4_8_1_1_U169(
    .din0(local_out_q0),
    .din1(local_out_1_q0),
    .din2(local_out_2_q0),
    .din3(local_out_3_q0),
    .din4(local_out_4_q0),
    .din5(local_out_5_q0),
    .din6(local_out_6_q0),
    .din7(local_out_7_q0),
    .din8(local_out_8_q0),
    .din9(local_out_9_q0),
    .din10(local_out_10_q0),
    .def(tmp_s_fu_382_p23),
    .sel(tmp_s_fu_382_p24),
    .dout(tmp_s_fu_382_p25)
);

otsu_threshold_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln342_fu_294_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_120 <= add_ln342_fu_300_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_120 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            phi_urem5_fu_116 <= 17'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            phi_urem5_fu_116 <= select_ln344_fu_370_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        tmp_reg_462 <= {{mul_ln342_fu_320_p2[32:20]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        tmp_s_reg_522 <= tmp_s_fu_382_p25;
    end
end

always @ (*) begin
    if (((icmp_ln342_fu_294_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 17'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_120;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        gmem1_blk_n_W = m_axi_gmem1_0_WREADY;
    end else begin
        gmem1_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_out_10_ce0_local = 1'b1;
    end else begin
        local_out_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_out_1_ce0_local = 1'b1;
    end else begin
        local_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_out_2_ce0_local = 1'b1;
    end else begin
        local_out_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_out_3_ce0_local = 1'b1;
    end else begin
        local_out_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_out_4_ce0_local = 1'b1;
    end else begin
        local_out_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_out_5_ce0_local = 1'b1;
    end else begin
        local_out_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_out_6_ce0_local = 1'b1;
    end else begin
        local_out_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_out_7_ce0_local = 1'b1;
    end else begin
        local_out_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_out_8_ce0_local = 1'b1;
    end else begin
        local_out_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_out_9_ce0_local = 1'b1;
    end else begin
        local_out_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_out_ce0_local = 1'b1;
    end else begin
        local_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        m_axi_gmem1_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem1_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln342_fu_300_p2 = (ap_sig_allocacmp_i_1 + 17'd1);

assign add_ln344_fu_358_p2 = (phi_urem5_fu_116 + 17'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem1_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_gmem1_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem1_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln342_fu_294_p2 = ((ap_sig_allocacmp_i_1 == 17'd65536) ? 1'b1 : 1'b0);

assign icmp_ln344_fu_364_p2 = ((phi_urem5_fu_116 == 17'd10) ? 1'b1 : 1'b0);

assign local_out_10_address0 = zext_ln342_fu_341_p1;

assign local_out_10_ce0 = local_out_10_ce0_local;

assign local_out_1_address0 = zext_ln342_fu_341_p1;

assign local_out_1_ce0 = local_out_1_ce0_local;

assign local_out_2_address0 = zext_ln342_fu_341_p1;

assign local_out_2_ce0 = local_out_2_ce0_local;

assign local_out_3_address0 = zext_ln342_fu_341_p1;

assign local_out_3_ce0 = local_out_3_ce0_local;

assign local_out_4_address0 = zext_ln342_fu_341_p1;

assign local_out_4_ce0 = local_out_4_ce0_local;

assign local_out_5_address0 = zext_ln342_fu_341_p1;

assign local_out_5_ce0 = local_out_5_ce0_local;

assign local_out_6_address0 = zext_ln342_fu_341_p1;

assign local_out_6_ce0 = local_out_6_ce0_local;

assign local_out_7_address0 = zext_ln342_fu_341_p1;

assign local_out_7_ce0 = local_out_7_ce0_local;

assign local_out_8_address0 = zext_ln342_fu_341_p1;

assign local_out_8_ce0 = local_out_8_ce0_local;

assign local_out_9_address0 = zext_ln342_fu_341_p1;

assign local_out_9_ce0 = local_out_9_ce0_local;

assign local_out_address0 = zext_ln342_fu_341_p1;

assign local_out_ce0 = local_out_ce0_local;

assign m_axi_gmem1_0_ARADDR = 64'd0;

assign m_axi_gmem1_0_ARBURST = 2'd0;

assign m_axi_gmem1_0_ARCACHE = 4'd0;

assign m_axi_gmem1_0_ARID = 1'd0;

assign m_axi_gmem1_0_ARLEN = 32'd0;

assign m_axi_gmem1_0_ARLOCK = 2'd0;

assign m_axi_gmem1_0_ARPROT = 3'd0;

assign m_axi_gmem1_0_ARQOS = 4'd0;

assign m_axi_gmem1_0_ARREGION = 4'd0;

assign m_axi_gmem1_0_ARSIZE = 3'd0;

assign m_axi_gmem1_0_ARUSER = 1'd0;

assign m_axi_gmem1_0_ARVALID = 1'b0;

assign m_axi_gmem1_0_AWADDR = 64'd0;

assign m_axi_gmem1_0_AWBURST = 2'd0;

assign m_axi_gmem1_0_AWCACHE = 4'd0;

assign m_axi_gmem1_0_AWID = 1'd0;

assign m_axi_gmem1_0_AWLEN = 32'd0;

assign m_axi_gmem1_0_AWLOCK = 2'd0;

assign m_axi_gmem1_0_AWPROT = 3'd0;

assign m_axi_gmem1_0_AWQOS = 4'd0;

assign m_axi_gmem1_0_AWREGION = 4'd0;

assign m_axi_gmem1_0_AWSIZE = 3'd0;

assign m_axi_gmem1_0_AWUSER = 1'd0;

assign m_axi_gmem1_0_AWVALID = 1'b0;

assign m_axi_gmem1_0_BREADY = 1'b0;

assign m_axi_gmem1_0_RREADY = 1'b0;

assign m_axi_gmem1_0_WDATA = tmp_s_reg_522;

assign m_axi_gmem1_0_WID = 1'd0;

assign m_axi_gmem1_0_WLAST = 1'b0;

assign m_axi_gmem1_0_WSTRB = 1'd1;

assign m_axi_gmem1_0_WUSER = 1'd0;

assign mul_ln342_fu_320_p0 = mul_ln342_fu_320_p00;

assign mul_ln342_fu_320_p00 = trunc_ln342_fu_312_p1;

assign mul_ln342_fu_320_p1 = 33'd95326;

assign select_ln344_fu_370_p3 = ((icmp_ln344_fu_364_p2[0:0] == 1'b1) ? 17'd0 : add_ln344_fu_358_p2);

assign tmp_s_fu_382_p23 = 'bx;

assign tmp_s_fu_382_p24 = phi_urem5_fu_116[3:0];

assign trunc_ln342_fu_312_p1 = ap_sig_allocacmp_i_1[15:0];

assign zext_ln342_fu_341_p1 = tmp_reg_462;

endmodule //otsu_threshold_top_otsu_threshold_top_Pipeline_WRITE_OUT
