// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module otsu_threshold_top_otsu_compute (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hist_address0,
        hist_ce0,
        hist_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] hist_address0;
output   hist_ce0;
input  [31:0] hist_q0;
output  [7:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] hist_address0;
reg hist_ce0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_start;
wire    grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_done;
wire    grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_idle;
wire    grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_ready;
wire   [7:0] grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_hist_address0;
wire    grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_hist_ce0;
wire   [47:0] grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_sum_total_out;
wire    grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_sum_total_out_ap_vld;
wire   [8:0] grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_grp_fu_53_p_din0;
wire   [31:0] grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_grp_fu_53_p_din1;
wire    grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_grp_fu_53_p_ce;
wire    grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_start;
wire    grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_done;
wire    grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_idle;
wire    grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_ready;
wire   [7:0] grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_hist_address0;
wire    grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_hist_ce0;
wire   [7:0] grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_best_thr_out;
wire    grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_best_thr_out_ap_vld;
wire   [8:0] grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_grp_fu_53_p_din0;
wire   [31:0] grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_grp_fu_53_p_din1;
wire    grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_grp_fu_53_p_ce;
reg    grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [39:0] grp_fu_53_p2;
reg   [8:0] grp_fu_53_p0;
reg   [31:0] grp_fu_53_p1;
reg    grp_fu_53_ce;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_start_reg = 1'b0;
#0 grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_start_reg = 1'b0;
end

otsu_threshold_top_otsu_compute_Pipeline_SUM_TOTAL grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_start),
    .ap_done(grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_done),
    .ap_idle(grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_idle),
    .ap_ready(grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_ready),
    .hist_address0(grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_hist_address0),
    .hist_ce0(grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_hist_ce0),
    .hist_q0(hist_q0),
    .sum_total_out(grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_sum_total_out),
    .sum_total_out_ap_vld(grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_sum_total_out_ap_vld),
    .grp_fu_53_p_din0(grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_grp_fu_53_p_din0),
    .grp_fu_53_p_din1(grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_grp_fu_53_p_din1),
    .grp_fu_53_p_dout0(grp_fu_53_p2),
    .grp_fu_53_p_ce(grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_grp_fu_53_p_ce)
);

otsu_threshold_top_otsu_compute_Pipeline_OTSU_SWEEP grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_start),
    .ap_done(grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_done),
    .ap_idle(grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_idle),
    .ap_ready(grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_ready),
    .hist_address0(grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_hist_address0),
    .hist_ce0(grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_hist_ce0),
    .hist_q0(hist_q0),
    .zext_ln59(grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_sum_total_out),
    .best_thr_out(grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_best_thr_out),
    .best_thr_out_ap_vld(grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_best_thr_out_ap_vld),
    .grp_fu_53_p_din0(grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_grp_fu_53_p_din0),
    .grp_fu_53_p_din1(grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_grp_fu_53_p_din1),
    .grp_fu_53_p_dout0(grp_fu_53_p2),
    .grp_fu_53_p_ce(grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_grp_fu_53_p_ce)
);

otsu_threshold_top_mul_9ns_32ns_40_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 40 ))
mul_9ns_32ns_40_2_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_53_p0),
    .din1(grp_fu_53_p1),
    .ce(grp_fu_53_ce),
    .dout(grp_fu_53_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_start_reg <= 1'b1;
        end else if ((grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_ready == 1'b1)) begin
            grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_start_reg <= 1'b1;
        end else if ((grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_ready == 1'b1)) begin
            grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_53_ce = grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_grp_fu_53_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_53_ce = grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_grp_fu_53_p_ce;
    end else begin
        grp_fu_53_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_53_p0 = grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_grp_fu_53_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_53_p0 = grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_grp_fu_53_p_din0;
    end else begin
        grp_fu_53_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_53_p1 = grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_grp_fu_53_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_53_p1 = grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_grp_fu_53_p_din1;
    end else begin
        grp_fu_53_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hist_address0 = grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_hist_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_address0 = grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_hist_address0;
    end else begin
        hist_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hist_ce0 = grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_hist_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_ce0 = grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_hist_ce0;
    end else begin
        hist_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_return = grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_best_thr_out;

assign grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_start = grp_otsu_compute_Pipeline_OTSU_SWEEP_fu_23_ap_start_reg;

assign grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_start = grp_otsu_compute_Pipeline_SUM_TOTAL_fu_16_ap_start_reg;

endmodule //otsu_threshold_top_otsu_compute
