// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module otsu_threshold_top_otsu_compute_Pipeline_OTSU_SWEEP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hist_address0,
        hist_ce0,
        hist_q0,
        zext_ln59,
        best_thr_out,
        best_thr_out_ap_vld,
        grp_fu_53_p_din0,
        grp_fu_53_p_din1,
        grp_fu_53_p_dout0,
        grp_fu_53_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] hist_address0;
output   hist_ce0;
input  [31:0] hist_q0;
input  [47:0] zext_ln59;
output  [7:0] best_thr_out;
output   best_thr_out_ap_vld;
output  [8:0] grp_fu_53_p_din0;
output  [31:0] grp_fu_53_p_din1;
input  [39:0] grp_fu_53_p_dout0;
output   grp_fu_53_p_ce;

reg ap_idle;
reg best_thr_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_enable_reg_pp0_iter40;
reg    ap_enable_reg_pp0_iter41;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln75_fu_163_p2;
wire   [0:0] icmp_ln79_fu_169_p2;
reg   [0:0] icmp_ln71_reg_341;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln59_cast_fu_102_p1;
reg   [63:0] zext_ln59_cast_reg_329;
reg   [8:0] t_1_reg_334;
wire   [0:0] icmp_ln71_fu_134_p2;
reg   [0:0] icmp_ln71_reg_341_pp0_iter1_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter2_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter3_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter4_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter5_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter6_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter7_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter8_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter9_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter10_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter11_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter12_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter13_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter14_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter15_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter16_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter17_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter18_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter19_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter20_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter21_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter22_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter23_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter24_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter25_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter26_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter27_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter28_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter29_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter30_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter31_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter32_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter33_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter34_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter35_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter36_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter37_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter38_reg;
reg   [0:0] icmp_ln71_reg_341_pp0_iter39_reg;
wire   [39:0] zext_ln73_fu_153_p1;
wire    ap_block_pp0_stage1_11001;
wire   [31:0] weight_bg_1_fu_157_p2;
reg   [31:0] weight_bg_1_reg_355;
reg   [0:0] icmp_ln75_reg_362;
reg   [0:0] icmp_ln75_reg_362_pp0_iter1_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter2_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter3_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter4_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter5_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter6_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter7_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter8_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter9_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter10_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter11_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter12_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter13_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter14_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter15_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter16_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter17_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter18_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter19_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter20_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter21_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter22_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter23_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter24_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter25_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter26_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter27_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter28_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter29_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter30_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter31_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter32_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter33_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter34_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter35_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter36_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter37_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter38_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter39_reg;
reg   [0:0] icmp_ln75_reg_362_pp0_iter40_reg;
reg   [0:0] icmp_ln79_reg_366;
reg   [0:0] icmp_ln79_reg_366_pp0_iter1_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter2_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter3_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter4_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter5_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter6_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter7_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter8_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter9_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter10_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter11_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter12_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter13_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter14_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter15_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter16_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter17_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter18_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter19_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter20_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter21_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter22_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter23_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter24_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter25_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter26_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter27_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter28_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter29_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter30_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter31_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter32_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter33_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter34_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter35_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter36_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter37_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter38_reg;
reg   [0:0] icmp_ln79_reg_366_pp0_iter39_reg;
wire   [39:0] zext_ln82_fu_175_p1;
wire   [7:0] trunc_ln103_fu_180_p1;
reg   [7:0] trunc_ln103_reg_375;
reg   [7:0] trunc_ln103_reg_375_pp0_iter1_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter2_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter3_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter4_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter5_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter6_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter7_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter8_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter9_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter10_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter11_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter12_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter13_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter14_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter15_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter16_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter17_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter18_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter19_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter20_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter21_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter22_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter23_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter24_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter25_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter26_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter27_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter28_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter29_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter30_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter31_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter32_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter33_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter34_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter35_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter36_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter37_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter38_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter39_reg;
reg   [7:0] trunc_ln103_reg_375_pp0_iter40_reg;
reg   [39:0] mul_ln82_reg_380;
wire   [31:0] weight_fg_fu_192_p2;
reg   [31:0] weight_fg_reg_385;
wire   [63:0] sum_bg_1_fu_203_p2;
wire   [63:0] sum_fg_fu_209_p2;
reg   [63:0] sum_fg_reg_395;
wire   [63:0] zext_ln94_fu_214_p1;
reg   [63:0] zext_ln94_reg_400;
reg   [63:0] zext_ln94_reg_400_pp0_iter2_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter3_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter4_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter5_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter6_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter7_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter8_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter9_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter10_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter11_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter12_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter13_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter14_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter15_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter16_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter17_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter18_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter19_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter20_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter21_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter22_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter23_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter24_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter25_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter26_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter27_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter28_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter29_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter30_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter31_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter32_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter33_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter34_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter35_reg;
reg   [63:0] zext_ln94_reg_400_pp0_iter36_reg;
wire   [63:0] zext_ln95_fu_228_p1;
reg   [63:0] zext_ln95_reg_406;
reg   [63:0] zext_ln95_reg_406_pp0_iter3_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter4_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter5_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter6_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter7_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter8_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter9_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter10_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter11_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter12_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter13_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter14_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter15_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter16_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter17_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter18_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter19_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter20_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter21_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter22_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter23_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter24_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter25_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter26_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter27_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter28_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter29_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter30_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter31_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter32_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter33_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter34_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter35_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter36_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter37_reg;
reg   [63:0] zext_ln95_reg_406_pp0_iter38_reg;
wire   [31:0] grp_fu_217_p2;
reg   [31:0] udiv_ln94_reg_412;
wire   [31:0] grp_fu_231_p2;
reg   [31:0] udiv_ln95_reg_417;
wire  signed [31:0] mean_diff_fu_242_p2;
wire   [31:0] grp_fu_94_p2;
reg   [31:0] mul_ln98_reg_428;
wire  signed [63:0] grp_fu_90_p2;
reg  signed [63:0] mul_ln97_reg_438;
wire   [63:0] grp_fu_98_p2;
reg   [63:0] var_between_reg_443;
reg    ap_condition_exit_pp0_iter1_stage1;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln71_fu_140_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] weight_bg_fu_40;
wire    ap_loop_init;
wire    ap_block_pp0_stage1;
reg   [8:0] t_fu_44;
wire   [8:0] t_2_fu_145_p2;
reg   [8:0] ap_sig_allocacmp_t_1;
reg   [7:0] best_thr_fu_48;
wire   [7:0] best_thr_1_fu_265_p3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter40_stage0;
reg    ap_idle_pp0_0to39;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg    ap_loop_exit_ready_pp0_iter39_reg;
reg    ap_loop_exit_ready_pp0_iter40_reg;
reg   [63:0] max_var_fu_52;
wire   [63:0] max_var_1_fu_272_p3;
reg   [63:0] sum_bg_fu_56;
wire    ap_block_pp0_stage0_01001;
reg    hist_ce0_local;
wire   [31:0] grp_fu_90_p0;
wire   [31:0] grp_fu_90_p1;
wire   [31:0] grp_fu_98_p1;
wire   [63:0] zext_ln82_1_fu_200_p1;
wire   [31:0] grp_fu_217_p1;
wire   [31:0] grp_fu_231_p1;
wire   [31:0] mean_bg_fu_236_p1;
wire   [31:0] mean_fg_fu_239_p1;
wire   [0:0] icmp_ln100_fu_260_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to41;
reg    ap_done_pending_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [63:0] grp_fu_217_p10;
wire   [63:0] grp_fu_231_p10;
wire   [63:0] grp_fu_90_p10;
reg    ap_condition_1079;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 ap_enable_reg_pp0_iter40 = 1'b0;
#0 ap_enable_reg_pp0_iter41 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 weight_bg_fu_40 = 32'd0;
#0 t_fu_44 = 9'd0;
#0 best_thr_fu_48 = 8'd0;
#0 max_var_fu_52 = 64'd0;
#0 sum_bg_fu_56 = 64'd0;
#0 ap_done_reg = 1'b0;
end

otsu_threshold_top_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_90_p0),
    .din1(grp_fu_90_p1),
    .ce(1'b1),
    .dout(grp_fu_90_p2)
);

otsu_threshold_top_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mean_diff_fu_242_p2),
    .din1(mean_diff_fu_242_p2),
    .ce(1'b1),
    .dout(grp_fu_94_p2)
);

otsu_threshold_top_mul_64s_32ns_64_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_64s_32ns_64_5_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_ln97_reg_438),
    .din1(grp_fu_98_p1),
    .ce(1'b1),
    .dout(grp_fu_98_p2)
);

otsu_threshold_top_udiv_64ns_32ns_32_68_1 #(
    .ID( 1 ),
    .NUM_STAGE( 68 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
udiv_64ns_32ns_32_68_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_bg_1_fu_203_p2),
    .din1(grp_fu_217_p1),
    .ce(1'b1),
    .dout(grp_fu_217_p2)
);

otsu_threshold_top_udiv_64ns_32ns_32_68_1 #(
    .ID( 1 ),
    .NUM_STAGE( 68 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
udiv_64ns_32ns_32_68_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_fg_reg_395),
    .din1(grp_fu_231_p1),
    .ce(1'b1),
    .dout(grp_fu_231_p2)
);

otsu_threshold_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter40_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage1)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter40 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter40 <= ap_enable_reg_pp0_iter39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter41 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter41 == 1'b1))) begin
            ap_enable_reg_pp0_iter41 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter41 <= ap_enable_reg_pp0_iter40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter17_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter18_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter19_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter20_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter21_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter22_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter23_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter24_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter25_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter26_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter27_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter28_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter29_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter30_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter31_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter32_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter33_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter34_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter35_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter36_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter37_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter38_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter39_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter39_reg <= ap_loop_exit_ready_pp0_iter38_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter40_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter40_reg <= ap_loop_exit_ready_pp0_iter39_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            best_thr_fu_48 <= 8'd0;
        end else if (((icmp_ln75_reg_362_pp0_iter40_reg == 1'd0) & (ap_enable_reg_pp0_iter41 == 1'b1))) begin
            best_thr_fu_48 <= best_thr_1_fu_265_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            max_var_fu_52 <= 64'd0;
        end else if (((icmp_ln75_reg_362_pp0_iter40_reg == 1'd0) & (ap_enable_reg_pp0_iter41 == 1'b1))) begin
            max_var_fu_52 <= max_var_1_fu_272_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_bg_fu_56 <= 64'd0;
    end else if (((icmp_ln79_reg_366 == 1'd0) & (icmp_ln75_reg_362 == 1'd0) & (icmp_ln71_reg_341_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        sum_bg_fu_56 <= sum_bg_1_fu_203_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_fu_44 <= 9'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (((icmp_ln71_reg_341 == 1'd0) & (icmp_ln75_fu_163_p2 == 1'd1)) | ((icmp_ln71_reg_341 == 1'd0) & (icmp_ln79_fu_169_p2 == 1'd0))))) begin
        t_fu_44 <= t_2_fu_145_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            weight_bg_fu_40 <= 32'd0;
        end else if ((1'b1 == ap_condition_1079)) begin
            weight_bg_fu_40 <= weight_bg_1_reg_355;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln71_reg_341 <= icmp_ln71_fu_134_p2;
        icmp_ln71_reg_341_pp0_iter10_reg <= icmp_ln71_reg_341_pp0_iter9_reg;
        icmp_ln71_reg_341_pp0_iter11_reg <= icmp_ln71_reg_341_pp0_iter10_reg;
        icmp_ln71_reg_341_pp0_iter12_reg <= icmp_ln71_reg_341_pp0_iter11_reg;
        icmp_ln71_reg_341_pp0_iter13_reg <= icmp_ln71_reg_341_pp0_iter12_reg;
        icmp_ln71_reg_341_pp0_iter14_reg <= icmp_ln71_reg_341_pp0_iter13_reg;
        icmp_ln71_reg_341_pp0_iter15_reg <= icmp_ln71_reg_341_pp0_iter14_reg;
        icmp_ln71_reg_341_pp0_iter16_reg <= icmp_ln71_reg_341_pp0_iter15_reg;
        icmp_ln71_reg_341_pp0_iter17_reg <= icmp_ln71_reg_341_pp0_iter16_reg;
        icmp_ln71_reg_341_pp0_iter18_reg <= icmp_ln71_reg_341_pp0_iter17_reg;
        icmp_ln71_reg_341_pp0_iter19_reg <= icmp_ln71_reg_341_pp0_iter18_reg;
        icmp_ln71_reg_341_pp0_iter1_reg <= icmp_ln71_reg_341;
        icmp_ln71_reg_341_pp0_iter20_reg <= icmp_ln71_reg_341_pp0_iter19_reg;
        icmp_ln71_reg_341_pp0_iter21_reg <= icmp_ln71_reg_341_pp0_iter20_reg;
        icmp_ln71_reg_341_pp0_iter22_reg <= icmp_ln71_reg_341_pp0_iter21_reg;
        icmp_ln71_reg_341_pp0_iter23_reg <= icmp_ln71_reg_341_pp0_iter22_reg;
        icmp_ln71_reg_341_pp0_iter24_reg <= icmp_ln71_reg_341_pp0_iter23_reg;
        icmp_ln71_reg_341_pp0_iter25_reg <= icmp_ln71_reg_341_pp0_iter24_reg;
        icmp_ln71_reg_341_pp0_iter26_reg <= icmp_ln71_reg_341_pp0_iter25_reg;
        icmp_ln71_reg_341_pp0_iter27_reg <= icmp_ln71_reg_341_pp0_iter26_reg;
        icmp_ln71_reg_341_pp0_iter28_reg <= icmp_ln71_reg_341_pp0_iter27_reg;
        icmp_ln71_reg_341_pp0_iter29_reg <= icmp_ln71_reg_341_pp0_iter28_reg;
        icmp_ln71_reg_341_pp0_iter2_reg <= icmp_ln71_reg_341_pp0_iter1_reg;
        icmp_ln71_reg_341_pp0_iter30_reg <= icmp_ln71_reg_341_pp0_iter29_reg;
        icmp_ln71_reg_341_pp0_iter31_reg <= icmp_ln71_reg_341_pp0_iter30_reg;
        icmp_ln71_reg_341_pp0_iter32_reg <= icmp_ln71_reg_341_pp0_iter31_reg;
        icmp_ln71_reg_341_pp0_iter33_reg <= icmp_ln71_reg_341_pp0_iter32_reg;
        icmp_ln71_reg_341_pp0_iter34_reg <= icmp_ln71_reg_341_pp0_iter33_reg;
        icmp_ln71_reg_341_pp0_iter35_reg <= icmp_ln71_reg_341_pp0_iter34_reg;
        icmp_ln71_reg_341_pp0_iter36_reg <= icmp_ln71_reg_341_pp0_iter35_reg;
        icmp_ln71_reg_341_pp0_iter37_reg <= icmp_ln71_reg_341_pp0_iter36_reg;
        icmp_ln71_reg_341_pp0_iter38_reg <= icmp_ln71_reg_341_pp0_iter37_reg;
        icmp_ln71_reg_341_pp0_iter39_reg <= icmp_ln71_reg_341_pp0_iter38_reg;
        icmp_ln71_reg_341_pp0_iter3_reg <= icmp_ln71_reg_341_pp0_iter2_reg;
        icmp_ln71_reg_341_pp0_iter4_reg <= icmp_ln71_reg_341_pp0_iter3_reg;
        icmp_ln71_reg_341_pp0_iter5_reg <= icmp_ln71_reg_341_pp0_iter4_reg;
        icmp_ln71_reg_341_pp0_iter6_reg <= icmp_ln71_reg_341_pp0_iter5_reg;
        icmp_ln71_reg_341_pp0_iter7_reg <= icmp_ln71_reg_341_pp0_iter6_reg;
        icmp_ln71_reg_341_pp0_iter8_reg <= icmp_ln71_reg_341_pp0_iter7_reg;
        icmp_ln71_reg_341_pp0_iter9_reg <= icmp_ln71_reg_341_pp0_iter8_reg;
        mul_ln82_reg_380 <= grp_fu_53_p_dout0;
        t_1_reg_334 <= ap_sig_allocacmp_t_1;
        udiv_ln94_reg_412 <= grp_fu_217_p2;
        zext_ln59_cast_reg_329[47 : 0] <= zext_ln59_cast_fu_102_p1[47 : 0];
        zext_ln95_reg_406[31 : 0] <= zext_ln95_fu_228_p1[31 : 0];
        zext_ln95_reg_406_pp0_iter10_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter9_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter11_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter10_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter12_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter11_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter13_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter12_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter14_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter13_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter15_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter14_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter16_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter15_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter17_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter16_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter18_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter17_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter19_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter18_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter20_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter19_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter21_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter20_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter22_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter21_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter23_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter22_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter24_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter23_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter25_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter24_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter26_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter25_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter27_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter26_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter28_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter27_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter29_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter28_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter30_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter29_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter31_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter30_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter32_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter31_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter33_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter32_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter34_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter33_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter35_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter34_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter36_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter35_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter37_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter36_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter38_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter37_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter3_reg[31 : 0] <= zext_ln95_reg_406[31 : 0];
        zext_ln95_reg_406_pp0_iter4_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter3_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter5_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter4_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter6_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter5_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter7_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter6_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter8_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter7_reg[31 : 0];
        zext_ln95_reg_406_pp0_iter9_reg[31 : 0] <= zext_ln95_reg_406_pp0_iter8_reg[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        icmp_ln75_reg_362 <= icmp_ln75_fu_163_p2;
        icmp_ln75_reg_362_pp0_iter10_reg <= icmp_ln75_reg_362_pp0_iter9_reg;
        icmp_ln75_reg_362_pp0_iter11_reg <= icmp_ln75_reg_362_pp0_iter10_reg;
        icmp_ln75_reg_362_pp0_iter12_reg <= icmp_ln75_reg_362_pp0_iter11_reg;
        icmp_ln75_reg_362_pp0_iter13_reg <= icmp_ln75_reg_362_pp0_iter12_reg;
        icmp_ln75_reg_362_pp0_iter14_reg <= icmp_ln75_reg_362_pp0_iter13_reg;
        icmp_ln75_reg_362_pp0_iter15_reg <= icmp_ln75_reg_362_pp0_iter14_reg;
        icmp_ln75_reg_362_pp0_iter16_reg <= icmp_ln75_reg_362_pp0_iter15_reg;
        icmp_ln75_reg_362_pp0_iter17_reg <= icmp_ln75_reg_362_pp0_iter16_reg;
        icmp_ln75_reg_362_pp0_iter18_reg <= icmp_ln75_reg_362_pp0_iter17_reg;
        icmp_ln75_reg_362_pp0_iter19_reg <= icmp_ln75_reg_362_pp0_iter18_reg;
        icmp_ln75_reg_362_pp0_iter1_reg <= icmp_ln75_reg_362;
        icmp_ln75_reg_362_pp0_iter20_reg <= icmp_ln75_reg_362_pp0_iter19_reg;
        icmp_ln75_reg_362_pp0_iter21_reg <= icmp_ln75_reg_362_pp0_iter20_reg;
        icmp_ln75_reg_362_pp0_iter22_reg <= icmp_ln75_reg_362_pp0_iter21_reg;
        icmp_ln75_reg_362_pp0_iter23_reg <= icmp_ln75_reg_362_pp0_iter22_reg;
        icmp_ln75_reg_362_pp0_iter24_reg <= icmp_ln75_reg_362_pp0_iter23_reg;
        icmp_ln75_reg_362_pp0_iter25_reg <= icmp_ln75_reg_362_pp0_iter24_reg;
        icmp_ln75_reg_362_pp0_iter26_reg <= icmp_ln75_reg_362_pp0_iter25_reg;
        icmp_ln75_reg_362_pp0_iter27_reg <= icmp_ln75_reg_362_pp0_iter26_reg;
        icmp_ln75_reg_362_pp0_iter28_reg <= icmp_ln75_reg_362_pp0_iter27_reg;
        icmp_ln75_reg_362_pp0_iter29_reg <= icmp_ln75_reg_362_pp0_iter28_reg;
        icmp_ln75_reg_362_pp0_iter2_reg <= icmp_ln75_reg_362_pp0_iter1_reg;
        icmp_ln75_reg_362_pp0_iter30_reg <= icmp_ln75_reg_362_pp0_iter29_reg;
        icmp_ln75_reg_362_pp0_iter31_reg <= icmp_ln75_reg_362_pp0_iter30_reg;
        icmp_ln75_reg_362_pp0_iter32_reg <= icmp_ln75_reg_362_pp0_iter31_reg;
        icmp_ln75_reg_362_pp0_iter33_reg <= icmp_ln75_reg_362_pp0_iter32_reg;
        icmp_ln75_reg_362_pp0_iter34_reg <= icmp_ln75_reg_362_pp0_iter33_reg;
        icmp_ln75_reg_362_pp0_iter35_reg <= icmp_ln75_reg_362_pp0_iter34_reg;
        icmp_ln75_reg_362_pp0_iter36_reg <= icmp_ln75_reg_362_pp0_iter35_reg;
        icmp_ln75_reg_362_pp0_iter37_reg <= icmp_ln75_reg_362_pp0_iter36_reg;
        icmp_ln75_reg_362_pp0_iter38_reg <= icmp_ln75_reg_362_pp0_iter37_reg;
        icmp_ln75_reg_362_pp0_iter39_reg <= icmp_ln75_reg_362_pp0_iter38_reg;
        icmp_ln75_reg_362_pp0_iter3_reg <= icmp_ln75_reg_362_pp0_iter2_reg;
        icmp_ln75_reg_362_pp0_iter40_reg <= icmp_ln75_reg_362_pp0_iter39_reg;
        icmp_ln75_reg_362_pp0_iter4_reg <= icmp_ln75_reg_362_pp0_iter3_reg;
        icmp_ln75_reg_362_pp0_iter5_reg <= icmp_ln75_reg_362_pp0_iter4_reg;
        icmp_ln75_reg_362_pp0_iter6_reg <= icmp_ln75_reg_362_pp0_iter5_reg;
        icmp_ln75_reg_362_pp0_iter7_reg <= icmp_ln75_reg_362_pp0_iter6_reg;
        icmp_ln75_reg_362_pp0_iter8_reg <= icmp_ln75_reg_362_pp0_iter7_reg;
        icmp_ln75_reg_362_pp0_iter9_reg <= icmp_ln75_reg_362_pp0_iter8_reg;
        icmp_ln79_reg_366 <= icmp_ln79_fu_169_p2;
        icmp_ln79_reg_366_pp0_iter10_reg <= icmp_ln79_reg_366_pp0_iter9_reg;
        icmp_ln79_reg_366_pp0_iter11_reg <= icmp_ln79_reg_366_pp0_iter10_reg;
        icmp_ln79_reg_366_pp0_iter12_reg <= icmp_ln79_reg_366_pp0_iter11_reg;
        icmp_ln79_reg_366_pp0_iter13_reg <= icmp_ln79_reg_366_pp0_iter12_reg;
        icmp_ln79_reg_366_pp0_iter14_reg <= icmp_ln79_reg_366_pp0_iter13_reg;
        icmp_ln79_reg_366_pp0_iter15_reg <= icmp_ln79_reg_366_pp0_iter14_reg;
        icmp_ln79_reg_366_pp0_iter16_reg <= icmp_ln79_reg_366_pp0_iter15_reg;
        icmp_ln79_reg_366_pp0_iter17_reg <= icmp_ln79_reg_366_pp0_iter16_reg;
        icmp_ln79_reg_366_pp0_iter18_reg <= icmp_ln79_reg_366_pp0_iter17_reg;
        icmp_ln79_reg_366_pp0_iter19_reg <= icmp_ln79_reg_366_pp0_iter18_reg;
        icmp_ln79_reg_366_pp0_iter1_reg <= icmp_ln79_reg_366;
        icmp_ln79_reg_366_pp0_iter20_reg <= icmp_ln79_reg_366_pp0_iter19_reg;
        icmp_ln79_reg_366_pp0_iter21_reg <= icmp_ln79_reg_366_pp0_iter20_reg;
        icmp_ln79_reg_366_pp0_iter22_reg <= icmp_ln79_reg_366_pp0_iter21_reg;
        icmp_ln79_reg_366_pp0_iter23_reg <= icmp_ln79_reg_366_pp0_iter22_reg;
        icmp_ln79_reg_366_pp0_iter24_reg <= icmp_ln79_reg_366_pp0_iter23_reg;
        icmp_ln79_reg_366_pp0_iter25_reg <= icmp_ln79_reg_366_pp0_iter24_reg;
        icmp_ln79_reg_366_pp0_iter26_reg <= icmp_ln79_reg_366_pp0_iter25_reg;
        icmp_ln79_reg_366_pp0_iter27_reg <= icmp_ln79_reg_366_pp0_iter26_reg;
        icmp_ln79_reg_366_pp0_iter28_reg <= icmp_ln79_reg_366_pp0_iter27_reg;
        icmp_ln79_reg_366_pp0_iter29_reg <= icmp_ln79_reg_366_pp0_iter28_reg;
        icmp_ln79_reg_366_pp0_iter2_reg <= icmp_ln79_reg_366_pp0_iter1_reg;
        icmp_ln79_reg_366_pp0_iter30_reg <= icmp_ln79_reg_366_pp0_iter29_reg;
        icmp_ln79_reg_366_pp0_iter31_reg <= icmp_ln79_reg_366_pp0_iter30_reg;
        icmp_ln79_reg_366_pp0_iter32_reg <= icmp_ln79_reg_366_pp0_iter31_reg;
        icmp_ln79_reg_366_pp0_iter33_reg <= icmp_ln79_reg_366_pp0_iter32_reg;
        icmp_ln79_reg_366_pp0_iter34_reg <= icmp_ln79_reg_366_pp0_iter33_reg;
        icmp_ln79_reg_366_pp0_iter35_reg <= icmp_ln79_reg_366_pp0_iter34_reg;
        icmp_ln79_reg_366_pp0_iter36_reg <= icmp_ln79_reg_366_pp0_iter35_reg;
        icmp_ln79_reg_366_pp0_iter37_reg <= icmp_ln79_reg_366_pp0_iter36_reg;
        icmp_ln79_reg_366_pp0_iter38_reg <= icmp_ln79_reg_366_pp0_iter37_reg;
        icmp_ln79_reg_366_pp0_iter39_reg <= icmp_ln79_reg_366_pp0_iter38_reg;
        icmp_ln79_reg_366_pp0_iter3_reg <= icmp_ln79_reg_366_pp0_iter2_reg;
        icmp_ln79_reg_366_pp0_iter4_reg <= icmp_ln79_reg_366_pp0_iter3_reg;
        icmp_ln79_reg_366_pp0_iter5_reg <= icmp_ln79_reg_366_pp0_iter4_reg;
        icmp_ln79_reg_366_pp0_iter6_reg <= icmp_ln79_reg_366_pp0_iter5_reg;
        icmp_ln79_reg_366_pp0_iter7_reg <= icmp_ln79_reg_366_pp0_iter6_reg;
        icmp_ln79_reg_366_pp0_iter8_reg <= icmp_ln79_reg_366_pp0_iter7_reg;
        icmp_ln79_reg_366_pp0_iter9_reg <= icmp_ln79_reg_366_pp0_iter8_reg;
        mul_ln97_reg_438 <= grp_fu_90_p2;
        mul_ln98_reg_428 <= grp_fu_94_p2;
        sum_fg_reg_395 <= sum_fg_fu_209_p2;
        trunc_ln103_reg_375 <= trunc_ln103_fu_180_p1;
        trunc_ln103_reg_375_pp0_iter10_reg <= trunc_ln103_reg_375_pp0_iter9_reg;
        trunc_ln103_reg_375_pp0_iter11_reg <= trunc_ln103_reg_375_pp0_iter10_reg;
        trunc_ln103_reg_375_pp0_iter12_reg <= trunc_ln103_reg_375_pp0_iter11_reg;
        trunc_ln103_reg_375_pp0_iter13_reg <= trunc_ln103_reg_375_pp0_iter12_reg;
        trunc_ln103_reg_375_pp0_iter14_reg <= trunc_ln103_reg_375_pp0_iter13_reg;
        trunc_ln103_reg_375_pp0_iter15_reg <= trunc_ln103_reg_375_pp0_iter14_reg;
        trunc_ln103_reg_375_pp0_iter16_reg <= trunc_ln103_reg_375_pp0_iter15_reg;
        trunc_ln103_reg_375_pp0_iter17_reg <= trunc_ln103_reg_375_pp0_iter16_reg;
        trunc_ln103_reg_375_pp0_iter18_reg <= trunc_ln103_reg_375_pp0_iter17_reg;
        trunc_ln103_reg_375_pp0_iter19_reg <= trunc_ln103_reg_375_pp0_iter18_reg;
        trunc_ln103_reg_375_pp0_iter1_reg <= trunc_ln103_reg_375;
        trunc_ln103_reg_375_pp0_iter20_reg <= trunc_ln103_reg_375_pp0_iter19_reg;
        trunc_ln103_reg_375_pp0_iter21_reg <= trunc_ln103_reg_375_pp0_iter20_reg;
        trunc_ln103_reg_375_pp0_iter22_reg <= trunc_ln103_reg_375_pp0_iter21_reg;
        trunc_ln103_reg_375_pp0_iter23_reg <= trunc_ln103_reg_375_pp0_iter22_reg;
        trunc_ln103_reg_375_pp0_iter24_reg <= trunc_ln103_reg_375_pp0_iter23_reg;
        trunc_ln103_reg_375_pp0_iter25_reg <= trunc_ln103_reg_375_pp0_iter24_reg;
        trunc_ln103_reg_375_pp0_iter26_reg <= trunc_ln103_reg_375_pp0_iter25_reg;
        trunc_ln103_reg_375_pp0_iter27_reg <= trunc_ln103_reg_375_pp0_iter26_reg;
        trunc_ln103_reg_375_pp0_iter28_reg <= trunc_ln103_reg_375_pp0_iter27_reg;
        trunc_ln103_reg_375_pp0_iter29_reg <= trunc_ln103_reg_375_pp0_iter28_reg;
        trunc_ln103_reg_375_pp0_iter2_reg <= trunc_ln103_reg_375_pp0_iter1_reg;
        trunc_ln103_reg_375_pp0_iter30_reg <= trunc_ln103_reg_375_pp0_iter29_reg;
        trunc_ln103_reg_375_pp0_iter31_reg <= trunc_ln103_reg_375_pp0_iter30_reg;
        trunc_ln103_reg_375_pp0_iter32_reg <= trunc_ln103_reg_375_pp0_iter31_reg;
        trunc_ln103_reg_375_pp0_iter33_reg <= trunc_ln103_reg_375_pp0_iter32_reg;
        trunc_ln103_reg_375_pp0_iter34_reg <= trunc_ln103_reg_375_pp0_iter33_reg;
        trunc_ln103_reg_375_pp0_iter35_reg <= trunc_ln103_reg_375_pp0_iter34_reg;
        trunc_ln103_reg_375_pp0_iter36_reg <= trunc_ln103_reg_375_pp0_iter35_reg;
        trunc_ln103_reg_375_pp0_iter37_reg <= trunc_ln103_reg_375_pp0_iter36_reg;
        trunc_ln103_reg_375_pp0_iter38_reg <= trunc_ln103_reg_375_pp0_iter37_reg;
        trunc_ln103_reg_375_pp0_iter39_reg <= trunc_ln103_reg_375_pp0_iter38_reg;
        trunc_ln103_reg_375_pp0_iter3_reg <= trunc_ln103_reg_375_pp0_iter2_reg;
        trunc_ln103_reg_375_pp0_iter40_reg <= trunc_ln103_reg_375_pp0_iter39_reg;
        trunc_ln103_reg_375_pp0_iter4_reg <= trunc_ln103_reg_375_pp0_iter3_reg;
        trunc_ln103_reg_375_pp0_iter5_reg <= trunc_ln103_reg_375_pp0_iter4_reg;
        trunc_ln103_reg_375_pp0_iter6_reg <= trunc_ln103_reg_375_pp0_iter5_reg;
        trunc_ln103_reg_375_pp0_iter7_reg <= trunc_ln103_reg_375_pp0_iter6_reg;
        trunc_ln103_reg_375_pp0_iter8_reg <= trunc_ln103_reg_375_pp0_iter7_reg;
        trunc_ln103_reg_375_pp0_iter9_reg <= trunc_ln103_reg_375_pp0_iter8_reg;
        udiv_ln95_reg_417 <= grp_fu_231_p2;
        var_between_reg_443 <= grp_fu_98_p2;
        weight_bg_1_reg_355 <= weight_bg_1_fu_157_p2;
        weight_fg_reg_385 <= weight_fg_fu_192_p2;
        zext_ln94_reg_400[31 : 0] <= zext_ln94_fu_214_p1[31 : 0];
        zext_ln94_reg_400_pp0_iter10_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter9_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter11_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter10_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter12_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter11_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter13_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter12_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter14_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter13_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter15_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter14_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter16_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter15_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter17_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter16_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter18_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter17_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter19_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter18_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter20_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter19_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter21_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter20_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter22_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter21_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter23_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter22_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter24_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter23_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter25_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter24_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter26_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter25_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter27_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter26_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter28_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter27_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter29_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter28_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter2_reg[31 : 0] <= zext_ln94_reg_400[31 : 0];
        zext_ln94_reg_400_pp0_iter30_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter29_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter31_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter30_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter32_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter31_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter33_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter32_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter34_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter33_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter35_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter34_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter36_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter35_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter3_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter2_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter4_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter3_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter5_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter4_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter6_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter5_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter7_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter6_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter8_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter7_reg[31 : 0];
        zext_ln94_reg_400_pp0_iter9_reg[31 : 0] <= zext_ln94_reg_400_pp0_iter8_reg[31 : 0];
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & ((icmp_ln71_reg_341 == 1'd1) | ((icmp_ln79_fu_169_p2 == 1'd1) & (icmp_ln75_fu_163_p2 == 1'd0))))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone) & ((icmp_ln71_reg_341_pp0_iter1_reg == 1'd1) | ((icmp_ln79_reg_366 == 1'd1) & (icmp_ln75_reg_362 == 1'd0))))) begin
        ap_condition_exit_pp0_iter1_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter40 == 1'b1) & ((icmp_ln71_reg_341_pp0_iter39_reg == 1'd1) | ((icmp_ln79_reg_366_pp0_iter39_reg == 1'd1) & (icmp_ln75_reg_362_pp0_iter39_reg == 1'd0))))) begin
        ap_condition_exit_pp0_iter40_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter40_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter40_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter40_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter39_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter38_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter37_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter36_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter35_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter34_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter33_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter32_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter31_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter30_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter29_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter28_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter27_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter26_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter25_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter24_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter23_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter22_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter21_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter20_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter19_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter18_reg 
    == 1'b0) & (ap_loop_exit_ready_pp0_iter17_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter16_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter15_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter13_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter41 == 1'b0) 
    & (ap_enable_reg_pp0_iter40 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) 
    & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0_0to39 = 1'b1;
    end else begin
        ap_idle_pp0_0to39 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter41 == 1'b0) & (ap_enable_reg_pp0_iter40 == 1'b0) 
    & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0_1to41 = 1'b1;
    end else begin
        ap_idle_pp0_1to41 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_t_1 = 9'd0;
    end else begin
        ap_sig_allocacmp_t_1 = t_fu_44;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter40_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & ((icmp_ln71_reg_341_pp0_iter39_reg == 1'd1) | ((icmp_ln79_reg_366_pp0_iter39_reg == 1'd1) & (icmp_ln75_reg_362_pp0_iter39_reg == 1'd0))))) begin
        best_thr_out_ap_vld = 1'b1;
    end else begin
        best_thr_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        hist_ce0_local = 1'b1;
    end else begin
        hist_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to39 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter40_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_idle_pp0_1to41 == 1'b1) & (ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1079 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln75_reg_362 == 1'd1) & (icmp_ln71_reg_341 == 1'd0)) | ((icmp_ln79_reg_366 == 1'd0) & (icmp_ln71_reg_341 == 1'd0))));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign best_thr_1_fu_265_p3 = ((icmp_ln100_fu_260_p2[0:0] == 1'b1) ? trunc_ln103_reg_375_pp0_iter40_reg : best_thr_fu_48);

assign best_thr_out = best_thr_fu_48;

assign grp_fu_217_p1 = grp_fu_217_p10;

assign grp_fu_217_p10 = weight_bg_1_reg_355;

assign grp_fu_231_p1 = grp_fu_231_p10;

assign grp_fu_231_p10 = weight_fg_reg_385;

assign grp_fu_53_p_ce = 1'b1;

assign grp_fu_53_p_din0 = zext_ln73_fu_153_p1;

assign grp_fu_53_p_din1 = zext_ln82_fu_175_p1;

assign grp_fu_90_p0 = zext_ln94_reg_400_pp0_iter36_reg;

assign grp_fu_90_p1 = grp_fu_90_p10;

assign grp_fu_90_p10 = mul_ln98_reg_428;

assign grp_fu_98_p1 = zext_ln95_reg_406_pp0_iter38_reg;

assign hist_address0 = zext_ln71_fu_140_p1;

assign hist_ce0 = hist_ce0_local;

assign icmp_ln100_fu_260_p2 = ((var_between_reg_443 > max_var_fu_52) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_134_p2 = ((ap_sig_allocacmp_t_1 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln75_fu_163_p2 = ((weight_bg_1_fu_157_p2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_169_p2 = ((weight_bg_1_fu_157_p2 == 32'd65536) ? 1'b1 : 1'b0);

assign max_var_1_fu_272_p3 = ((icmp_ln100_fu_260_p2[0:0] == 1'b1) ? var_between_reg_443 : max_var_fu_52);

assign mean_bg_fu_236_p1 = udiv_ln94_reg_412[31:0];

assign mean_diff_fu_242_p2 = (mean_bg_fu_236_p1 - mean_fg_fu_239_p1);

assign mean_fg_fu_239_p1 = udiv_ln95_reg_417[31:0];

assign sum_bg_1_fu_203_p2 = (zext_ln82_1_fu_200_p1 + sum_bg_fu_56);

assign sum_fg_fu_209_p2 = (zext_ln59_cast_reg_329 - sum_bg_1_fu_203_p2);

assign t_2_fu_145_p2 = (t_1_reg_334 + 9'd1);

assign trunc_ln103_fu_180_p1 = t_1_reg_334[7:0];

assign weight_bg_1_fu_157_p2 = (hist_q0 + weight_bg_fu_40);

assign weight_fg_fu_192_p2 = (32'd65536 - weight_bg_1_reg_355);

assign zext_ln59_cast_fu_102_p1 = zext_ln59;

assign zext_ln71_fu_140_p1 = ap_sig_allocacmp_t_1;

assign zext_ln73_fu_153_p1 = t_1_reg_334;

assign zext_ln82_1_fu_200_p1 = mul_ln82_reg_380;

assign zext_ln82_fu_175_p1 = hist_q0;

assign zext_ln94_fu_214_p1 = weight_bg_1_reg_355;

assign zext_ln95_fu_228_p1 = weight_fg_reg_385;

always @ (posedge ap_clk) begin
    zext_ln59_cast_reg_329[63:48] <= 16'b0000000000000000;
    zext_ln94_reg_400[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter2_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter3_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter4_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter5_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter6_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter7_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter8_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter9_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter10_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter11_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter12_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter13_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter14_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter15_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter16_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter17_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter18_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter19_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter20_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter21_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter22_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter23_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter24_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter25_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter26_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter27_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter28_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter29_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter30_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter31_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter32_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter33_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter34_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter35_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln94_reg_400_pp0_iter36_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter3_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter4_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter5_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter6_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter7_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter8_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter9_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter10_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter11_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter12_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter13_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter14_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter15_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter16_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter17_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter18_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter19_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter20_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter21_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter22_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter23_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter24_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter25_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter26_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter27_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter28_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter29_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter30_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter31_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter32_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter33_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter34_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter35_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter36_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter37_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln95_reg_406_pp0_iter38_reg[63:32] <= 32'b00000000000000000000000000000000;
end

endmodule //otsu_threshold_top_otsu_compute_Pipeline_OTSU_SWEEP
