
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xotsu_threshold_top.h"

/*
* The configuration table for devices
*/

XOtsu_threshold_top_Config XOtsu_threshold_top_ConfigTable[XPAR_XOTSU_THRESHOLD_TOP_NUM_INSTANCES] =
{
	{
		XPAR_HLS_OTSU_0_DEVICE_ID,
		XPAR_HLS_OTSU_0_S_AXI_CONTROL_BASEADDR,
		XPAR_HLS_OTSU_0_S_AXI_CONTROL_R_BASEADDR
	}
};


