////////////////////////////////////////////////////////////////////////////////
// top_module.v
// -------------
// Top-level wrapper for standalone testing (without Vivado block design).
//
// NOTE: When using the MicroBlaze block design generated by build.tcl,
// this module is NOT used. The block design wrapper (microblaze_soc_wrapper)
// becomes the synthesis top. This module is provided for RTL-only testing.
//
// Target: Artix-7 xc7a100tcsg324-1 (Nexys A7-100T) @ 100 MHz
////////////////////////////////////////////////////////////////////////////////

module top_module (
    input  wire       clk_100mhz,    // 100 MHz system clock
    input  wire       reset_n,       // Active-low reset (button)

    // UART
    input  wire       uart_rxd,      // UART receive
    output wire       uart_txd,      // UART transmit

    // Status LEDs (active-high)
    //   led[0] = heartbeat
    //   led[1] = processing
    //   led[2] = mode bit 0
    //   led[3] = mode bit 1
    //   led[4] = done
    output wire [4:0] led
);

    // =========================================================================
    // Clock and Reset
    // =========================================================================

    wire sys_clk;
    wire sys_rst;

    // Use the 100 MHz input directly (no PLL needed for this clock rate)
    assign sys_clk = clk_100mhz;

    // Two-stage synchronizer to prevent metastability on async reset
    reg reset_sync_1, reset_sync_2;
    always @(posedge sys_clk or negedge reset_n) begin
        if (~reset_n) begin
            reset_sync_1 <= 1'b1;
            reset_sync_2 <= 1'b1;
        end else begin
            reset_sync_1 <= 1'b0;
            reset_sync_2 <= reset_sync_1;
        end
    end
    assign sys_rst = reset_sync_2;

    // =========================================================================
    // LED Status Indicators
    // =========================================================================

    // Simple heartbeat for standalone testing
    reg [25:0] heartbeat_counter;
    always @(posedge sys_clk or posedge sys_rst) begin
        if (sys_rst)
            heartbeat_counter <= 26'd0;
        else
            heartbeat_counter <= heartbeat_counter + 1'b1;
    end

    // Default LED outputs for standalone testing
    assign led[0] = heartbeat_counter[25];  // ~1.5 Hz blink (heartbeat)
    assign led[1] = 1'b0;                   // processing (inactive)
    assign led[2] = 1'b0;                   // mode[0]
    assign led[3] = 1'b0;                   // mode[1]
    assign led[4] = 1'b0;                   // done

    // UART loopback for testing
    assign uart_txd = uart_rxd;

    // =========================================================================
    // NOTE: Full System Integration
    // =========================================================================
    // When building the complete system, use build.tcl which:
    // 1. Creates a MicroBlaze block design (microblaze_soc)
    // 2. Generates the wrapper (microblaze_soc_wrapper)
    // 3. Sets microblaze_soc_wrapper as the synthesis top
    //
    // In that flow, this top_module.v is NOT used.
    // LEDs are driven directly by axi_gpio_0 in the block design.
    // =========================================================================

endmodule
