-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity otsu_threshold_top_erode_3x3_linebuf is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    src_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    src_ce0 : OUT STD_LOGIC;
    src_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    dst_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    dst_ce1 : OUT STD_LOGIC;
    dst_we1 : OUT STD_LOGIC;
    dst_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of otsu_threshold_top_erode_3x3_linebuf is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv15_4100 : STD_LOGIC_VECTOR (14 downto 0) := "100000100000000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv8_FE : STD_LOGIC_VECTOR (7 downto 0) := "11111110";
    constant ap_const_lv7_7E : STD_LOGIC_VECTOR (6 downto 0) := "1111110";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln241_fu_193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal icmp_ln241_reg_605 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal col_fu_210_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal col_reg_609 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln_fu_214_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_reg_614 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_619 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln267_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln267_reg_629 : STD_LOGIC_VECTOR (0 downto 0);
    signal line_buf_addr_reg_634 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln276_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln276_reg_640 : STD_LOGIC_VECTOR (0 downto 0);
    signal line_buf_1_addr_reg_644 : STD_LOGIC_VECTOR (6 downto 0);
    signal and_ln290_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln290_reg_650 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln290_reg_650_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln290_reg_650_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_col_fu_325_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_col_reg_654 : STD_LOGIC_VECTOR (6 downto 0);
    signal out_col_reg_654_pp0_iter2_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal v22_fu_408_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal v22_reg_659 : STD_LOGIC_VECTOR (7 downto 0);
    signal v22_reg_659_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal m01_fu_422_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal m01_reg_665 : STD_LOGIC_VECTOR (7 downto 0);
    signal m23_fu_436_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal m23_reg_671 : STD_LOGIC_VECTOR (7 downto 0);
    signal m45_fu_450_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal m45_reg_677 : STD_LOGIC_VECTOR (7 downto 0);
    signal m67_fu_464_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal m67_reg_683 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln320_fu_472_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln320_reg_689 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln320_reg_689_pp0_iter2_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal m01234567_fu_532_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal m01234567_reg_694 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal line_buf_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buf_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buf_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buf_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal line_buf_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buf_1_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_phi_mux_v12_phi_fu_177_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_v12_reg_173 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_v12_reg_173 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln241_fu_205_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln287_fu_248_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln320_fu_557_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_fu_72 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_39_fu_76 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_40_fu_80 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal i_fu_84 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal add_ln241_fu_199_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_4 : STD_LOGIC_VECTOR (14 downto 0);
    signal empty_41_fu_88 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_43_fu_304_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal v11_fu_92 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_42_fu_96 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal new_pixel_1_fu_296_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_ce0_local : STD_LOGIC;
    signal line_buf_ce0_local : STD_LOGIC;
    signal line_buf_we1_local : STD_LOGIC;
    signal line_buf_ce1_local : STD_LOGIC;
    signal line_buf_1_ce0_local : STD_LOGIC;
    signal line_buf_1_we1_local : STD_LOGIC;
    signal line_buf_1_ce1_local : STD_LOGIC;
    signal dst_we1_local : STD_LOGIC;
    signal result_fu_544_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal dst_ce1_local : STD_LOGIC;
    signal tmp_497_fu_232_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_498_fu_260_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln290_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_row_fu_320_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln296_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln296_1_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln296_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln302_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln302_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal v00_fu_348_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal v01_fu_356_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln208_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal v02_fu_364_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal v10_fu_372_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln208_1_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln208_2_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal v20_fu_392_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal v21_fu_400_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln208_3_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln208_4_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln208_5_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal m0123_fu_510_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal m4567_fu_520_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln208_6_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln208_7_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln_fu_551_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_enable_operation_36 : BOOLEAN;
    signal ap_enable_state1_pp0_iter0_stage0 : BOOLEAN;
    signal ap_enable_operation_55 : BOOLEAN;
    signal ap_enable_state2_pp0_iter1_stage0 : BOOLEAN;
    signal ap_predicate_op58_store_state2 : BOOLEAN;
    signal ap_enable_operation_58 : BOOLEAN;
    signal ap_predicate_op40_load_state1 : BOOLEAN;
    signal ap_enable_operation_40 : BOOLEAN;
    signal ap_predicate_op57_load_state2 : BOOLEAN;
    signal ap_enable_operation_57 : BOOLEAN;
    signal ap_enable_operation_60 : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_162 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component otsu_threshold_top_erode_3x3_linebuf_line_buf_RAM_S2P_LUTRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component otsu_threshold_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    line_buf_U : component otsu_threshold_top_erode_3x3_linebuf_line_buf_RAM_S2P_LUTRAM_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => line_buf_address0,
        ce0 => line_buf_ce0_local,
        q0 => line_buf_q0,
        address1 => line_buf_address1,
        ce1 => line_buf_ce1_local,
        we1 => line_buf_we1_local,
        d1 => line_buf_1_q0);

    line_buf_1_U : component otsu_threshold_top_erode_3x3_linebuf_line_buf_RAM_S2P_LUTRAM_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => line_buf_1_address0,
        ce0 => line_buf_1_ce0_local,
        q0 => line_buf_1_q0,
        address1 => line_buf_1_address1,
        ce1 => line_buf_1_ce1_local,
        we1 => line_buf_1_we1_local,
        d1 => new_pixel_1_fu_296_p3);

    flow_control_loop_pipe_sequential_init_U : component otsu_threshold_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_v12_reg_173_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_162)) then
                if (((icmp_ln276_fu_254_p2 = ap_const_lv1_1) and (icmp_ln241_fu_193_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_v12_reg_173 <= ap_const_lv8_FF;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_v12_reg_173 <= ap_phi_reg_pp0_iter0_v12_reg_173;
                end if;
            end if; 
        end if;
    end process;

    i_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln241_fu_193_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1))) then 
                    i_fu_84 <= add_ln241_fu_199_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_84 <= ap_const_lv15_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln290_reg_650 <= and_ln290_fu_276_p2;
                and_ln290_reg_650_pp0_iter1_reg <= and_ln290_reg_650;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                col_reg_609 <= col_fu_210_p1;
                icmp_ln241_reg_605 <= icmp_ln241_fu_193_p2;
                icmp_ln267_reg_629 <= icmp_ln267_fu_242_p2;
                icmp_ln276_reg_640 <= icmp_ln276_fu_254_p2;
                line_buf_1_addr_reg_644 <= zext_ln287_fu_248_p1(7 - 1 downto 0);
                line_buf_addr_reg_634 <= zext_ln287_fu_248_p1(7 - 1 downto 0);
                m01_reg_665 <= m01_fu_422_p3;
                m23_reg_671 <= m23_fu_436_p3;
                m45_reg_677 <= m45_fu_450_p3;
                m67_reg_683 <= m67_fu_464_p3;
                out_col_reg_654 <= out_col_fu_325_p2;
                tmp_reg_619 <= ap_sig_allocacmp_i_4(14 downto 14);
                trunc_ln320_reg_689 <= trunc_ln320_fu_472_p1;
                trunc_ln_reg_614 <= ap_sig_allocacmp_i_4(14 downto 7);
                v22_reg_659 <= v22_fu_408_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln290_reg_650_pp0_iter2_reg <= and_ln290_reg_650_pp0_iter1_reg;
                m01234567_reg_694 <= m01234567_fu_532_p3;
                out_col_reg_654_pp0_iter2_reg <= out_col_reg_654;
                trunc_ln320_reg_689_pp0_iter2_reg <= trunc_ln320_reg_689;
                v22_reg_659_pp0_iter2_reg <= v22_reg_659;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln241_reg_605 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                empty_39_fu_76 <= v11_fu_92;
                empty_40_fu_80 <= empty_42_fu_96;
                empty_41_fu_88 <= empty_43_fu_304_p3;
                empty_42_fu_96 <= new_pixel_1_fu_296_p3;
                empty_fu_72 <= empty_41_fu_88;
                v11_fu_92 <= ap_phi_mux_v12_phi_fu_177_p4;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln241_fu_199_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_4) + unsigned(ap_const_lv15_1));
    add_ln_fu_551_p3 <= (trunc_ln320_reg_689_pp0_iter2_reg & out_col_reg_654_pp0_iter2_reg);
    and_ln290_fu_276_p2 <= (icmp_ln290_fu_270_p2 and icmp_ln267_fu_242_p2);
    and_ln296_fu_342_p2 <= (icmp_ln296_fu_330_p2 and icmp_ln296_1_fu_336_p2);
    and_ln302_fu_386_p2 <= (icmp_ln302_fu_380_p2 and icmp_ln296_1_fu_336_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_162_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_162 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln241_fu_193_p2, ap_start_int)
    begin
        if (((icmp_ln241_fu_193_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln241_reg_605)
    begin
        if (((icmp_ln241_reg_605 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_enable_operation_36_assign_proc : process(icmp_ln241_fu_193_p2)
    begin
                ap_enable_operation_36 <= (icmp_ln241_fu_193_p2 = ap_const_lv1_0);
    end process;


    ap_enable_operation_40_assign_proc : process(ap_predicate_op40_load_state1)
    begin
                ap_enable_operation_40 <= (ap_predicate_op40_load_state1 = ap_const_boolean_1);
    end process;


    ap_enable_operation_55_assign_proc : process(icmp_ln241_reg_605)
    begin
                ap_enable_operation_55 <= (icmp_ln241_reg_605 = ap_const_lv1_0);
    end process;


    ap_enable_operation_57_assign_proc : process(ap_predicate_op57_load_state2)
    begin
                ap_enable_operation_57 <= (ap_predicate_op57_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_58_assign_proc : process(ap_predicate_op58_store_state2)
    begin
                ap_enable_operation_58 <= (ap_predicate_op58_store_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_60_assign_proc : process(icmp_ln241_reg_605)
    begin
                ap_enable_operation_60 <= (icmp_ln241_reg_605 = ap_const_lv1_0);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_enable_state1_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_start_int)
    begin
                ap_enable_state1_pp0_iter0_stage0 <= ((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state2_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state2_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_v12_phi_fu_177_p4_assign_proc : process(icmp_ln241_reg_605, icmp_ln276_reg_640, line_buf_1_q0, ap_phi_reg_pp0_iter1_v12_reg_173)
    begin
        if (((icmp_ln276_reg_640 = ap_const_lv1_0) and (icmp_ln241_reg_605 = ap_const_lv1_0))) then 
            ap_phi_mux_v12_phi_fu_177_p4 <= line_buf_1_q0;
        else 
            ap_phi_mux_v12_phi_fu_177_p4 <= ap_phi_reg_pp0_iter1_v12_reg_173;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_v12_reg_173 <= "XXXXXXXX";

    ap_predicate_op40_load_state1_assign_proc : process(icmp_ln241_fu_193_p2, icmp_ln276_fu_254_p2)
    begin
                ap_predicate_op40_load_state1 <= ((icmp_ln276_fu_254_p2 = ap_const_lv1_0) and (icmp_ln241_fu_193_p2 = ap_const_lv1_0));
    end process;


    ap_predicate_op57_load_state2_assign_proc : process(icmp_ln241_reg_605, icmp_ln276_reg_640)
    begin
                ap_predicate_op57_load_state2 <= ((icmp_ln276_reg_640 = ap_const_lv1_0) and (icmp_ln241_reg_605 = ap_const_lv1_0));
    end process;


    ap_predicate_op58_store_state2_assign_proc : process(icmp_ln241_reg_605, icmp_ln276_reg_640)
    begin
                ap_predicate_op58_store_state2 <= ((icmp_ln276_reg_640 = ap_const_lv1_0) and (icmp_ln241_reg_605 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_84, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_4 <= ap_const_lv15_0;
        else 
            ap_sig_allocacmp_i_4 <= i_fu_84;
        end if; 
    end process;

    col_fu_210_p1 <= ap_sig_allocacmp_i_4(7 - 1 downto 0);
    dst_address1 <= zext_ln320_fu_557_p1(14 - 1 downto 0);
    dst_ce1 <= dst_ce1_local;

    dst_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            dst_ce1_local <= ap_const_logic_1;
        else 
            dst_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    dst_d1 <= result_fu_544_p3;
    dst_we1 <= dst_we1_local;

    dst_we1_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, and_ln290_reg_650_pp0_iter2_reg)
    begin
        if (((ap_const_lv1_1 = and_ln290_reg_650_pp0_iter2_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            dst_we1_local <= ap_const_logic_1;
        else 
            dst_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_43_fu_304_p3 <= 
        line_buf_q0 when (icmp_ln267_reg_629(0) = '1') else 
        ap_const_lv8_FF;
    icmp_ln208_1_fu_430_p2 <= "1" when (unsigned(v02_fu_364_p3) < unsigned(v10_fu_372_p3)) else "0";
    icmp_ln208_2_fu_444_p2 <= "1" when (unsigned(v11_fu_92) < unsigned(ap_phi_mux_v12_phi_fu_177_p4)) else "0";
    icmp_ln208_3_fu_458_p2 <= "1" when (unsigned(v20_fu_392_p3) < unsigned(v21_fu_400_p3)) else "0";
    icmp_ln208_4_fu_506_p2 <= "1" when (unsigned(m01_reg_665) < unsigned(m23_reg_671)) else "0";
    icmp_ln208_5_fu_516_p2 <= "1" when (unsigned(m45_reg_677) < unsigned(m67_reg_683)) else "0";
    icmp_ln208_6_fu_526_p2 <= "1" when (unsigned(m0123_fu_510_p3) < unsigned(m4567_fu_520_p3)) else "0";
    icmp_ln208_7_fu_540_p2 <= "1" when (unsigned(m01234567_reg_694) < unsigned(v22_reg_659_pp0_iter2_reg)) else "0";
    icmp_ln208_fu_416_p2 <= "1" when (unsigned(v00_fu_348_p3) < unsigned(v01_fu_356_p3)) else "0";
    icmp_ln241_fu_193_p2 <= "1" when (ap_sig_allocacmp_i_4 = ap_const_lv15_4100) else "0";
    icmp_ln267_fu_242_p2 <= "0" when (tmp_497_fu_232_p4 = ap_const_lv7_0) else "1";
    icmp_ln276_fu_254_p2 <= "1" when (trunc_ln_fu_214_p4 = ap_const_lv8_0) else "0";
    icmp_ln290_fu_270_p2 <= "0" when (tmp_498_fu_260_p4 = ap_const_lv6_0) else "1";
    icmp_ln296_1_fu_336_p2 <= "0" when (out_col_fu_325_p2 = ap_const_lv7_0) else "1";
    icmp_ln296_fu_330_p2 <= "1" when (signed(out_row_fu_320_p2) > signed(ap_const_lv8_0)) else "0";
    icmp_ln302_fu_380_p2 <= "0" when (out_row_fu_320_p2 = ap_const_lv8_7F) else "1";
    line_buf_1_address0 <= zext_ln287_fu_248_p1(7 - 1 downto 0);
    line_buf_1_address1 <= line_buf_1_addr_reg_644;

    line_buf_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_1_ce0_local <= ap_const_logic_1;
        else 
            line_buf_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_1_ce1_local <= ap_const_logic_1;
        else 
            line_buf_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_1_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln241_reg_605, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln241_reg_605 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_1_we1_local <= ap_const_logic_1;
        else 
            line_buf_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_address0 <= zext_ln287_fu_248_p1(7 - 1 downto 0);
    line_buf_address1 <= line_buf_addr_reg_634;

    line_buf_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_ce0_local <= ap_const_logic_1;
        else 
            line_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_ce1_local <= ap_const_logic_1;
        else 
            line_buf_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln241_reg_605, ap_block_pp0_stage0_11001, icmp_ln276_reg_640)
    begin
        if (((icmp_ln276_reg_640 = ap_const_lv1_0) and (icmp_ln241_reg_605 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            line_buf_we1_local <= ap_const_logic_1;
        else 
            line_buf_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    m01234567_fu_532_p3 <= 
        m0123_fu_510_p3 when (icmp_ln208_6_fu_526_p2(0) = '1') else 
        m4567_fu_520_p3;
    m0123_fu_510_p3 <= 
        m01_reg_665 when (icmp_ln208_4_fu_506_p2(0) = '1') else 
        m23_reg_671;
    m01_fu_422_p3 <= 
        v00_fu_348_p3 when (icmp_ln208_fu_416_p2(0) = '1') else 
        v01_fu_356_p3;
    m23_fu_436_p3 <= 
        v02_fu_364_p3 when (icmp_ln208_1_fu_430_p2(0) = '1') else 
        v10_fu_372_p3;
    m4567_fu_520_p3 <= 
        m45_reg_677 when (icmp_ln208_5_fu_516_p2(0) = '1') else 
        m67_reg_683;
    m45_fu_450_p3 <= 
        v11_fu_92 when (icmp_ln208_2_fu_444_p2(0) = '1') else 
        ap_phi_mux_v12_phi_fu_177_p4;
    m67_fu_464_p3 <= 
        v20_fu_392_p3 when (icmp_ln208_3_fu_458_p2(0) = '1') else 
        v21_fu_400_p3;
    new_pixel_1_fu_296_p3 <= 
        ap_const_lv8_FF when (tmp_reg_619(0) = '1') else 
        src_q0;
    out_col_fu_325_p2 <= std_logic_vector(unsigned(col_reg_609) + unsigned(ap_const_lv7_7E));
    out_row_fu_320_p2 <= std_logic_vector(unsigned(trunc_ln_reg_614) + unsigned(ap_const_lv8_FE));
    result_fu_544_p3 <= 
        m01234567_reg_694 when (icmp_ln208_7_fu_540_p2(0) = '1') else 
        v22_reg_659_pp0_iter2_reg;
    src_address0 <= zext_ln241_fu_205_p1(14 - 1 downto 0);
    src_ce0 <= src_ce0_local;

    src_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_ce0_local <= ap_const_logic_1;
        else 
            src_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_497_fu_232_p4 <= ap_sig_allocacmp_i_4(14 downto 8);
    tmp_498_fu_260_p4 <= ap_sig_allocacmp_i_4(6 downto 1);
    trunc_ln320_fu_472_p1 <= out_row_fu_320_p2(7 - 1 downto 0);
    trunc_ln_fu_214_p4 <= ap_sig_allocacmp_i_4(14 downto 7);
    v00_fu_348_p3 <= 
        empty_fu_72 when (and_ln296_fu_342_p2(0) = '1') else 
        ap_const_lv8_FF;
    v01_fu_356_p3 <= 
        empty_41_fu_88 when (icmp_ln296_fu_330_p2(0) = '1') else 
        ap_const_lv8_FF;
    v02_fu_364_p3 <= 
        empty_43_fu_304_p3 when (icmp_ln296_fu_330_p2(0) = '1') else 
        ap_const_lv8_FF;
    v10_fu_372_p3 <= 
        empty_39_fu_76 when (icmp_ln296_1_fu_336_p2(0) = '1') else 
        ap_const_lv8_FF;
    v20_fu_392_p3 <= 
        empty_40_fu_80 when (and_ln302_fu_386_p2(0) = '1') else 
        ap_const_lv8_FF;
    v21_fu_400_p3 <= 
        empty_42_fu_96 when (icmp_ln302_fu_380_p2(0) = '1') else 
        ap_const_lv8_FF;
    v22_fu_408_p3 <= 
        new_pixel_1_fu_296_p3 when (icmp_ln302_fu_380_p2(0) = '1') else 
        ap_const_lv8_FF;
    zext_ln241_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_4),64));
    zext_ln287_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_fu_210_p1),64));
    zext_ln320_fu_557_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln_fu_551_p3),64));
end behav;
