-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity otsu_threshold_top_otsu_threshold_top_Pipeline_COUNT_FINAL is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    local_out_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    local_out_ce0 : OUT STD_LOGIC;
    local_out_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    local_out_1_ce0 : OUT STD_LOGIC;
    local_out_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    local_out_2_ce0 : OUT STD_LOGIC;
    local_out_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_3_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    local_out_3_ce0 : OUT STD_LOGIC;
    local_out_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_4_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    local_out_4_ce0 : OUT STD_LOGIC;
    local_out_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_5_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    local_out_5_ce0 : OUT STD_LOGIC;
    local_out_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_6_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    local_out_6_ce0 : OUT STD_LOGIC;
    local_out_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_7_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    local_out_7_ce0 : OUT STD_LOGIC;
    local_out_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_8_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    local_out_8_ce0 : OUT STD_LOGIC;
    local_out_8_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_9_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    local_out_9_ce0 : OUT STD_LOGIC;
    local_out_9_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_10_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    local_out_10_ce0 : OUT STD_LOGIC;
    local_out_10_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    fg_out : OUT STD_LOGIC_VECTOR (14 downto 0);
    fg_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of otsu_threshold_top_otsu_threshold_top_Pipeline_COUNT_FINAL is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv15_4000 : STD_LOGIC_VECTOR (14 downto 0) := "100000000000000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv30_BA2F : STD_LOGIC_VECTOR (29 downto 0) := "000000000000001011101000101111";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv15_B : STD_LOGIC_VECTOR (14 downto 0) := "000000000001011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln330_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln330_reg_435 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_494 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln328_fu_294_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal phi_urem_fu_74 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln332_fu_334_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal phi_mul_fu_78 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln328_fu_278_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal fg_fu_82 : STD_LOGIC_VECTOR (14 downto 0);
    signal fg_1_fu_391_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal i_fu_86 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln330_fu_269_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_fu_284_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln332_fu_322_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln332_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_346_p12 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_346_p13 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln333_fu_388_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component otsu_threshold_top_mux_11_4_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        din8 : IN STD_LOGIC_VECTOR (7 downto 0);
        din9 : IN STD_LOGIC_VECTOR (7 downto 0);
        din10 : IN STD_LOGIC_VECTOR (7 downto 0);
        din11 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component otsu_threshold_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_11_4_8_1_1_U143 : component otsu_threshold_top_mux_11_4_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => local_out_q0,
        din1 => local_out_1_q0,
        din2 => local_out_2_q0,
        din3 => local_out_3_q0,
        din4 => local_out_4_q0,
        din5 => local_out_5_q0,
        din6 => local_out_6_q0,
        din7 => local_out_7_q0,
        din8 => local_out_8_q0,
        din9 => local_out_9_q0,
        din10 => local_out_10_q0,
        din11 => tmp_s_fu_346_p12,
        dout => tmp_s_fu_346_p13);

    flow_control_loop_pipe_sequential_init_U : component otsu_threshold_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    fg_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    fg_fu_82 <= ap_const_lv15_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    fg_fu_82 <= fg_1_fu_391_p2;
                end if;
            end if; 
        end if;
    end process;

    i_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_86 <= ap_const_lv15_0;
                elsif (((icmp_ln330_fu_263_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_fu_86 <= add_ln330_fu_269_p2;
                end if;
            end if; 
        end if;
    end process;

    phi_mul_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    phi_mul_fu_78 <= ap_const_lv30_0;
                elsif (((icmp_ln330_fu_263_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    phi_mul_fu_78 <= add_ln328_fu_278_p2;
                end if;
            end if; 
        end if;
    end process;

    phi_urem_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    phi_urem_fu_74 <= ap_const_lv15_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    phi_urem_fu_74 <= select_ln332_fu_334_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln330_reg_435 <= icmp_ln330_fu_263_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln333_reg_494 <= icmp_ln333_fu_374_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln328_fu_278_p2 <= std_logic_vector(unsigned(phi_mul_fu_78) + unsigned(ap_const_lv30_BA2F));
    add_ln330_fu_269_p2 <= std_logic_vector(unsigned(i_fu_86) + unsigned(ap_const_lv15_1));
    add_ln332_fu_322_p2 <= std_logic_vector(unsigned(phi_urem_fu_74) + unsigned(ap_const_lv15_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln330_fu_263_p2)
    begin
        if (((icmp_ln330_fu_263_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    fg_1_fu_391_p2 <= std_logic_vector(unsigned(zext_ln333_fu_388_p1) + unsigned(fg_fu_82));
    fg_out <= fg_fu_82;

    fg_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln330_reg_435)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln330_reg_435 = ap_const_lv1_1))) then 
            fg_out_ap_vld <= ap_const_logic_1;
        else 
            fg_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln330_fu_263_p2 <= "1" when (i_fu_86 = ap_const_lv15_4000) else "0";
    icmp_ln332_fu_328_p2 <= "1" when (unsigned(add_ln332_fu_322_p2) < unsigned(ap_const_lv15_B)) else "0";
    icmp_ln333_fu_374_p2 <= "0" when (tmp_s_fu_346_p13 = ap_const_lv8_0) else "1";
    local_out_10_address0 <= zext_ln328_fu_294_p1(11 - 1 downto 0);

    local_out_10_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_10_ce0 <= ap_const_logic_1;
        else 
            local_out_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_out_1_address0 <= zext_ln328_fu_294_p1(11 - 1 downto 0);

    local_out_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_1_ce0 <= ap_const_logic_1;
        else 
            local_out_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_out_2_address0 <= zext_ln328_fu_294_p1(11 - 1 downto 0);

    local_out_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_2_ce0 <= ap_const_logic_1;
        else 
            local_out_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_out_3_address0 <= zext_ln328_fu_294_p1(11 - 1 downto 0);

    local_out_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_3_ce0 <= ap_const_logic_1;
        else 
            local_out_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_out_4_address0 <= zext_ln328_fu_294_p1(11 - 1 downto 0);

    local_out_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_4_ce0 <= ap_const_logic_1;
        else 
            local_out_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_out_5_address0 <= zext_ln328_fu_294_p1(11 - 1 downto 0);

    local_out_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_5_ce0 <= ap_const_logic_1;
        else 
            local_out_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_out_6_address0 <= zext_ln328_fu_294_p1(11 - 1 downto 0);

    local_out_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_6_ce0 <= ap_const_logic_1;
        else 
            local_out_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_out_7_address0 <= zext_ln328_fu_294_p1(11 - 1 downto 0);

    local_out_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_7_ce0 <= ap_const_logic_1;
        else 
            local_out_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_out_8_address0 <= zext_ln328_fu_294_p1(11 - 1 downto 0);

    local_out_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_8_ce0 <= ap_const_logic_1;
        else 
            local_out_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_out_9_address0 <= zext_ln328_fu_294_p1(11 - 1 downto 0);

    local_out_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_9_ce0 <= ap_const_logic_1;
        else 
            local_out_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_out_address0 <= zext_ln328_fu_294_p1(11 - 1 downto 0);

    local_out_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_ce0 <= ap_const_logic_1;
        else 
            local_out_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln332_fu_334_p3 <= 
        add_ln332_fu_322_p2 when (icmp_ln332_fu_328_p2(0) = '1') else 
        ap_const_lv15_0;
    tmp_fu_284_p4 <= phi_mul_fu_78(29 downto 19);
    tmp_s_fu_346_p12 <= phi_urem_fu_74(4 - 1 downto 0);
    zext_ln328_fu_294_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_284_p4),64));
    zext_ln333_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln333_reg_494),15));
end behav;
