-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity otsu_threshold_top_otsu_threshold_top_Pipeline_COUNT_FINAL is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    local_out_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    local_out_ce0 : OUT STD_LOGIC;
    local_out_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    local_out_1_ce0 : OUT STD_LOGIC;
    local_out_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_2_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    local_out_2_ce0 : OUT STD_LOGIC;
    local_out_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_3_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    local_out_3_ce0 : OUT STD_LOGIC;
    local_out_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_4_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    local_out_4_ce0 : OUT STD_LOGIC;
    local_out_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_5_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    local_out_5_ce0 : OUT STD_LOGIC;
    local_out_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_6_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    local_out_6_ce0 : OUT STD_LOGIC;
    local_out_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_7_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    local_out_7_ce0 : OUT STD_LOGIC;
    local_out_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_8_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    local_out_8_ce0 : OUT STD_LOGIC;
    local_out_8_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_9_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    local_out_9_ce0 : OUT STD_LOGIC;
    local_out_9_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    local_out_10_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    local_out_10_ce0 : OUT STD_LOGIC;
    local_out_10_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    fg_out : OUT STD_LOGIC_VECTOR (16 downto 0);
    fg_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of otsu_threshold_top_otsu_threshold_top_Pipeline_COUNT_FINAL is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv17_10000 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv33_1745E : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000010111010001011110";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv17_A : STD_LOGIC_VECTOR (16 downto 0) := "00000000000001010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln330_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln330_reg_464 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln330_reg_464_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_468 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln333_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln333_reg_528 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln328_fu_317_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal phi_urem_fu_96 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal select_ln332_fu_346_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal fg_fu_100 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal fg_1_fu_427_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal i_fu_104 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal add_ln330_fu_282_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_sig_allocacmp_i_4 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal local_out_ce0_local : STD_LOGIC;
    signal local_out_1_ce0_local : STD_LOGIC;
    signal local_out_2_ce0_local : STD_LOGIC;
    signal local_out_3_ce0_local : STD_LOGIC;
    signal local_out_4_ce0_local : STD_LOGIC;
    signal local_out_5_ce0_local : STD_LOGIC;
    signal local_out_6_ce0_local : STD_LOGIC;
    signal local_out_7_ce0_local : STD_LOGIC;
    signal local_out_8_ce0_local : STD_LOGIC;
    signal local_out_9_ce0_local : STD_LOGIC;
    signal local_out_10_ce0_local : STD_LOGIC;
    signal trunc_ln328_fu_288_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln328_fu_296_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln328_fu_296_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln328_fu_296_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal icmp_ln332_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln332_fu_334_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_s_fu_358_p23 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_358_p24 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_358_p25 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln333_fu_424_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln328_fu_296_p00 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_s_fu_358_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_358_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_358_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_358_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_358_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_358_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_358_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_358_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_358_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_358_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_358_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component otsu_threshold_top_mul_16ns_18ns_33_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        dout : OUT STD_LOGIC_VECTOR (32 downto 0) );
    end component;


    component otsu_threshold_top_sparsemux_23_4_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        din8 : IN STD_LOGIC_VECTOR (7 downto 0);
        din9 : IN STD_LOGIC_VECTOR (7 downto 0);
        din10 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component otsu_threshold_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_16ns_18ns_33_1_1_U154 : component otsu_threshold_top_mul_16ns_18ns_33_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 18,
        dout_WIDTH => 33)
    port map (
        din0 => mul_ln328_fu_296_p0,
        din1 => mul_ln328_fu_296_p1,
        dout => mul_ln328_fu_296_p2);

    sparsemux_23_4_8_1_1_U155 : component otsu_threshold_top_sparsemux_23_4_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 8,
        CASE1 => "0001",
        din1_WIDTH => 8,
        CASE2 => "0010",
        din2_WIDTH => 8,
        CASE3 => "0011",
        din3_WIDTH => 8,
        CASE4 => "0100",
        din4_WIDTH => 8,
        CASE5 => "0101",
        din5_WIDTH => 8,
        CASE6 => "0110",
        din6_WIDTH => 8,
        CASE7 => "0111",
        din7_WIDTH => 8,
        CASE8 => "1000",
        din8_WIDTH => 8,
        CASE9 => "1001",
        din9_WIDTH => 8,
        CASE10 => "1010",
        din10_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => local_out_q0,
        din1 => local_out_1_q0,
        din2 => local_out_2_q0,
        din3 => local_out_3_q0,
        din4 => local_out_4_q0,
        din5 => local_out_5_q0,
        din6 => local_out_6_q0,
        din7 => local_out_7_q0,
        din8 => local_out_8_q0,
        din9 => local_out_9_q0,
        din10 => local_out_10_q0,
        def => tmp_s_fu_358_p23,
        sel => tmp_s_fu_358_p24,
        dout => tmp_s_fu_358_p25);

    flow_control_loop_pipe_sequential_init_U : component otsu_threshold_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    fg_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    fg_fu_100 <= ap_const_lv17_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    fg_fu_100 <= fg_1_fu_427_p2;
                end if;
            end if; 
        end if;
    end process;

    i_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln330_fu_276_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_104 <= add_ln330_fu_282_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_104 <= ap_const_lv17_0;
                end if;
            end if; 
        end if;
    end process;

    phi_urem_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    phi_urem_fu_96 <= ap_const_lv17_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    phi_urem_fu_96 <= select_ln332_fu_346_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln330_reg_464 <= icmp_ln330_fu_276_p2;
                icmp_ln330_reg_464_pp0_iter1_reg <= icmp_ln330_reg_464;
                tmp_reg_468 <= mul_ln328_fu_296_p2(32 downto 20);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln333_reg_528 <= icmp_ln333_fu_410_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln330_fu_282_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_4) + unsigned(ap_const_lv17_1));
    add_ln332_fu_334_p2 <= std_logic_vector(unsigned(phi_urem_fu_96) + unsigned(ap_const_lv17_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln330_fu_276_p2)
    begin
        if (((icmp_ln330_fu_276_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_104)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_4 <= ap_const_lv17_0;
        else 
            ap_sig_allocacmp_i_4 <= i_fu_104;
        end if; 
    end process;

    fg_1_fu_427_p2 <= std_logic_vector(unsigned(zext_ln333_fu_424_p1) + unsigned(fg_fu_100));
    fg_out <= fg_fu_100;

    fg_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln330_reg_464_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln330_reg_464_pp0_iter1_reg = ap_const_lv1_1))) then 
            fg_out_ap_vld <= ap_const_logic_1;
        else 
            fg_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln330_fu_276_p2 <= "1" when (ap_sig_allocacmp_i_4 = ap_const_lv17_10000) else "0";
    icmp_ln332_fu_340_p2 <= "1" when (phi_urem_fu_96 = ap_const_lv17_A) else "0";
    icmp_ln333_fu_410_p2 <= "0" when (tmp_s_fu_358_p25 = ap_const_lv8_0) else "1";
    local_out_10_address0 <= zext_ln328_fu_317_p1(13 - 1 downto 0);
    local_out_10_ce0 <= local_out_10_ce0_local;

    local_out_10_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_10_ce0_local <= ap_const_logic_1;
        else 
            local_out_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_out_1_address0 <= zext_ln328_fu_317_p1(13 - 1 downto 0);
    local_out_1_ce0 <= local_out_1_ce0_local;

    local_out_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_1_ce0_local <= ap_const_logic_1;
        else 
            local_out_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_out_2_address0 <= zext_ln328_fu_317_p1(13 - 1 downto 0);
    local_out_2_ce0 <= local_out_2_ce0_local;

    local_out_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_2_ce0_local <= ap_const_logic_1;
        else 
            local_out_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_out_3_address0 <= zext_ln328_fu_317_p1(13 - 1 downto 0);
    local_out_3_ce0 <= local_out_3_ce0_local;

    local_out_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_3_ce0_local <= ap_const_logic_1;
        else 
            local_out_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_out_4_address0 <= zext_ln328_fu_317_p1(13 - 1 downto 0);
    local_out_4_ce0 <= local_out_4_ce0_local;

    local_out_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_4_ce0_local <= ap_const_logic_1;
        else 
            local_out_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_out_5_address0 <= zext_ln328_fu_317_p1(13 - 1 downto 0);
    local_out_5_ce0 <= local_out_5_ce0_local;

    local_out_5_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_5_ce0_local <= ap_const_logic_1;
        else 
            local_out_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_out_6_address0 <= zext_ln328_fu_317_p1(13 - 1 downto 0);
    local_out_6_ce0 <= local_out_6_ce0_local;

    local_out_6_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_6_ce0_local <= ap_const_logic_1;
        else 
            local_out_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_out_7_address0 <= zext_ln328_fu_317_p1(13 - 1 downto 0);
    local_out_7_ce0 <= local_out_7_ce0_local;

    local_out_7_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_7_ce0_local <= ap_const_logic_1;
        else 
            local_out_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_out_8_address0 <= zext_ln328_fu_317_p1(13 - 1 downto 0);
    local_out_8_ce0 <= local_out_8_ce0_local;

    local_out_8_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_8_ce0_local <= ap_const_logic_1;
        else 
            local_out_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_out_9_address0 <= zext_ln328_fu_317_p1(13 - 1 downto 0);
    local_out_9_ce0 <= local_out_9_ce0_local;

    local_out_9_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_9_ce0_local <= ap_const_logic_1;
        else 
            local_out_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_out_address0 <= zext_ln328_fu_317_p1(13 - 1 downto 0);
    local_out_ce0 <= local_out_ce0_local;

    local_out_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_out_ce0_local <= ap_const_logic_1;
        else 
            local_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln328_fu_296_p0 <= mul_ln328_fu_296_p00(16 - 1 downto 0);
    mul_ln328_fu_296_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln328_fu_288_p1),33));
    mul_ln328_fu_296_p1 <= ap_const_lv33_1745E(18 - 1 downto 0);
    select_ln332_fu_346_p3 <= 
        ap_const_lv17_0 when (icmp_ln332_fu_340_p2(0) = '1') else 
        add_ln332_fu_334_p2;
    tmp_s_fu_358_p23 <= "XXXXXXXX";
    tmp_s_fu_358_p24 <= phi_urem_fu_96(4 - 1 downto 0);
    trunc_ln328_fu_288_p1 <= ap_sig_allocacmp_i_4(16 - 1 downto 0);
    zext_ln328_fu_317_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_468),64));
    zext_ln333_fu_424_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln333_reg_528),17));
end behav;
